const SUPABASE_URL='https://uvdnejmdqgwdcipctyur.supabase.co';
const SUPABASE_KEY='sb_publishable_Afn5llFEgcHD4Uhmt8N4pA_W0T_NHZk';
let api=null;try{api=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}catch(error){console.error(error)}

const CATEGORIES=['Sistemas web','Aplicativos','Jogos','Projetos de redes','Projetos de IA','Automações','Projetos extensionistas','Projetos integradores','TCCs em desenvolvimento','Interfaces e protótipos','GitHub e portfólio pessoal'];
const PRESENTATIONS=['Banner','Notebook próprio','TV ou tela','Demonstração prática','Outro formato'];
const state={config:null,participants:[{nome:'',email:'',whatsapp:''}],sent:false};
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
const svg=path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
function wordmark(){return `<a class="wordmark" href="/"><span class="wordmark-mark">${svg('<path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14"/>')}</span><span class="wordmark-copy"><span class="wordmark-name"><b>Coordenação</b><em>TADS e EDC - AEMS</em></span></span></a>`}
function header(){return `<header class="public-header"><div class="public-header-inner">${wordmark()}<div class="header-links"><a href="/">Portal dos cursos</a></div></div></header>`}
function toast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),4300)}
function hero(){return `<section class="inovatec-hero"><p class="inovatec-kicker">Semana Acadêmica · Dia 3</p><h1>INOVATEC Showcase <span>Mostre o que sabe fazer</span></h1><p>Apresente uma ideia, habilidade ou projeto em um Portfólio Pitch e compartilhe seu protagonismo com a comunidade acadêmica.</p><span class="inovatec-day">DIA 3 · PROTAGONISMO</span></section>`}
function categories(){return `<section class="inovatec-categories"><h2>O que pode ser apresentado?</h2><p>Escolha a categoria que melhor representa sua proposta.</p><div class="category-cloud">${CATEGORIES.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</div></section>`}
function participantRow(item,index){return `<div class="participant-card" data-participant="${index}"><div class="participant-head"><b>${index===0?'Responsável pela inscrição':'Integrante '+(index+1)}</b>${index?`<button type="button" class="participant-remove" data-remove="${index}">Remover</button>`:''}</div><div class="form-row"><label><b>Nome completo</b><input name="nome" maxlength="160" value="${escapeHtml(item.nome)}" required></label><label><b>E-mail</b><input type="email" name="email" maxlength="180" value="${escapeHtml(item.email)}" required></label><label><b>WhatsApp</b><input type="tel" name="whatsapp" maxlength="24" value="${escapeHtml(item.whatsapp)}" placeholder="(67) 99999-9999" required></label></div></div>`}
function closed(){document.getElementById('app').innerHTML=`${header()}<main class="inovatec-main">${hero()}<div class="inovatec-closed"><h2>Inscrições encerradas</h2><p>As inscrições para o INOVATEC Showcase não estão abertas no momento. Acompanhe os canais da coordenação para novas informações.</p></div></main>`}
function success(){document.getElementById('app').innerHTML=`${header()}<main class="inovatec-main">${hero()}<div class="inovatec-success"><h2>Inscrição recebida!</h2><p>A proposta do grupo foi registrada. A organização poderá entrar em contato pelo e-mail ou WhatsApp informado.</p><button class="submit-form" id="new-entry">Fazer outra inscrição</button></div></main>`;document.getElementById('new-entry').onclick=()=>{state.sent=false;state.participants=[{nome:'',email:'',whatsapp:''}];render()}}
function form(){const max=state.config?.max_participantes||4;return `${header()}<main class="inovatec-main">${hero()}${categories()}<article class="public-form inovatec-form"><span class="form-badge">INSCRIÇÃO</span><h2>Cadastre a apresentação do grupo</h2><p>Grupos de uma a ${max} pessoas. Informe os dados de todos os participantes.</p><form id="inovatec-form"><div class="form-row"><label><b>Título da apresentação</b><input name="titulo" maxlength="180" required></label><label><b>Curso</b><select name="curso" required><option value="">Selecione</option><option value="ADS">Análise e Desenvolvimento de Sistemas</option><option value="EDC">Engenharia de Computação</option><option value="OUTRO">Outro curso</option></select></label></div><div class="inovatec-section"><h3>Proposta</h3><p>Conte o que será apresentado e como o público poderá conhecer o trabalho.</p><div class="form-row"><label><b>Categoria</b><select name="categoria" required><option value="">Selecione</option>${CATEGORIES.map(item=>`<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join('')}</select></label><label><b>Link do projeto ou portfólio <small>(opcional)</small></b><input name="link" type="url" maxlength="500" placeholder="https://"></label></div><label><b>Breve resumo do que será apresentado</b><textarea name="resumo" minlength="30" maxlength="1500" required></textarea></label></div><div class="inovatec-section"><h3>Forma de apresentação</h3><p>Marque todas as opções que serão utilizadas.</p><div class="presentation-options">${PRESENTATIONS.map(item=>`<label><input type="checkbox" name="formato" value="${escapeHtml(item)}"><span>${escapeHtml(item)}</span></label>`).join('')}</div><label><b>Materiais, equipamentos ou apoio necessários</b><textarea name="necessidades" maxlength="1000" placeholder="Ex.: mesa, tomada, TV, cabo HDMI ou nenhum material adicional."></textarea></label></div><div class="inovatec-section"><h3>Participantes</h3><p>O primeiro integrante será o contato principal da inscrição.</p><div class="participant-list">${state.participants.map(participantRow).join('')}</div><button class="add-participant" type="button" id="add-participant" ${state.participants.length>=max?'disabled':''}>+ Adicionar integrante</button></div><div class="privacy-hint">Os dados de contato serão usados somente pela organização da Semana Acadêmica e não ficarão públicos.</div><button class="submit-form" id="submit-inovatec" type="submit">Enviar inscrição</button></form></article></main>`}
function syncParticipants(){state.participants=[...document.querySelectorAll('[data-participant]')].map(row=>({nome:row.querySelector('[name="nome"]').value,email:row.querySelector('[name="email"]').value,whatsapp:row.querySelector('[name="whatsapp"]').value}))}
function render(){if(state.sent)return success();if(!state.config?.inscricoes_abertas)return closed();document.getElementById('app').innerHTML=form();bind()}
function bind(){document.getElementById('add-participant')?.addEventListener('click',()=>{syncParticipants();if(state.participants.length<(state.config.max_participantes||4)){state.participants.push({nome:'',email:'',whatsapp:''});render()}});document.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{syncParticipants();state.participants.splice(Number(button.dataset.remove),1);render()}));document.getElementById('inovatec-form')?.addEventListener('submit',submit)}
function validEmail(value){return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)}
async function submit(event){event.preventDefault();syncParticipants();const formEl=event.target,titulo=formEl.elements.titulo.value.trim(),curso=formEl.elements.curso.value,categoria=formEl.elements.categoria.value,resumo=formEl.elements.resumo.value.trim(),link=formEl.elements.link.value.trim(),necessidades=formEl.elements.necessidades.value.trim(),formatos=[...formEl.querySelectorAll('[name="formato"]:checked')].map(input=>input.value),participants=state.participants.map(item=>({nome:item.nome.trim(),email:item.email.trim().toLowerCase(),whatsapp:item.whatsapp.trim()}));if(titulo.length<3)return toast('Informe o título da apresentação.');if(!curso||!categoria)return toast('Selecione o curso e a categoria.');if(resumo.length<30)return toast('O resumo precisa ter pelo menos 30 caracteres.');if(!formatos.length)return toast('Selecione ao menos uma forma de apresentação.');for(const item of participants){if(item.nome.length<3||!validEmail(item.email)||item.whatsapp.replace(/\D/g,'').length<10)return toast('Preencha nome, e-mail e WhatsApp válidos para todos os participantes.')}const button=document.getElementById('submit-inovatec');button.disabled=true;button.textContent='Enviando…';try{const {data,error}=await api.rpc('enviar_inscricao_inovatec',{p_titulo:titulo,p_curso:curso,p_categoria:categoria,p_resumo:resumo,p_formatos:formatos,p_necessidades:necessidades||null,p_link:link||null,p_participantes:participants});if(error)throw error;if(!data)throw new Error('A inscrição não foi confirmada.');state.sent=true;render()}catch(error){console.error(error);toast('Não foi possível enviar: '+(error?.message||error))}finally{if(document.getElementById('submit-inovatec')){button.disabled=false;button.textContent='Enviar inscrição'}}}
async function boot(){document.getElementById('app').innerHTML=`${header()}<div class="inovatec-loading">Carregando inscrições…</div>`;try{if(!api)throw new Error('Serviço indisponível');const {data,error}=await api.from('inovatec_configuracoes').select('*').eq('id',1).maybeSingle();if(error)throw error;state.config=data||{inscricoes_abertas:false,max_participantes:4};render()}catch(error){console.error(error);document.getElementById('app').innerHTML=`${header()}<main class="inovatec-main"><div class="inovatec-closed"><h2>Não foi possível carregar</h2><p>Atualize a página e tente novamente em instantes.</p></div></main>`}}
window.addEventListener('load',boot);
