window.ECEAEMS_PROGRAMACAO={
  edicao:'XVIII ECEAEMS 2026',
  modalidade:'Apresentação oral',
  sala:'Sala 1',
  cursos:['Engenharia de Computação','Tecnologia em Análise e Desenvolvimento de Sistemas'],
  meet:'https://meet.google.com/rmu-ggbp-rve',
  avaliadores:['Alex Sander Amorim Borges','Bruno Gabriel Correa Pereira','Vinicius Duarte Tessari'],
  trabalhos:[
    {
      titulo:'Arquitetura híbrida aplicada a sistemas automotivos',
      autores:['Rafael Carvalho de Souza','Alberto Alexandre Suave Silva','Gustavo Maldanis Zanini','Muriel Vieira Teixeira'],
      resumo:'Sistemas operacionais automotivos modernos exigem alta estabilidade, segurança, isolamento de recursos e capacidade de expansão para gerir funções integradas como painel digital, multimídia, navegação e sensores. Este trabalho apresenta o NovaOS, um sistema operacional projetado sobre uma arquitetura híbrida para responder a esses requisitos específicos do cenário automotivo. A arquitetura híbrida combina a eficiência do modelo monolítico à tolerância a falhas do microkernel, mantendo o escalonamento, o gerenciamento de memória, a segurança e o sistema de arquivos no núcleo centralizado, enquanto isola serviços não críticos, como áudio, conectividade de rede e interface de utilizador, em processos separados. Esta estrutura garante baixo tempo de resposta em operações essenciais e reduz a propagação de falhas em componentes secundários. A comunicação entre as aplicações e o núcleo ocorre através de APIs e chamadas de sistema (syscalls) bem definidas, assegurando que operações privilegiadas sejam controladas pelo kernel e prevenindo o acesso direto ao hardware. Em testes de simulação de falhas em drivers, o isolamento de serviços provou ser eficaz para evitar travamentos gerais no painel e na navegação, permitindo a recuperação pontual do componente afetado sem a necessidade de reinicialização total do sistema. A solução demonstra ser equilibrada, viabilizando a evolução contínua e a adição de novos dispositivos sem comprometer a confiabilidade do veículo.',
      palavras:'Sistema operacional automotivo; arquitetura híbrida; chamadas de sistema; isolamento de falhas; NovaOS.'
    },
    {
      titulo:'ESP32 e Internet das Coisas: conceitos, arquitetura e aplicação prática em automação residencial',
      autores:['Robert Willian Vicente Rodrigues','Muriel Vieira Teixeira'],
      resumo:'O avanço da Internet das Coisas (IoT) tem ampliado a utilização de sistemas embarcados capazes de coletar informações do ambiente, processar dados, comunicar-se por redes e controlar diferentes dispositivos. Nesse contexto, o ESP32 destaca-se como uma plataforma amplamente utilizada no desenvolvimento de projetos de IoT e automação devido aos seus recursos de processamento, conectividade e possibilidade de integração com sensores e atuadores. Este trabalho tem como objetivo apresentar os principais conceitos relacionados ao ESP32, abordando suas características, arquitetura, capacidade de processamento, interfaces de comunicação e possibilidades de programação, relacionando esses conhecimentos às suas aplicações práticas. Como demonstração, será apresentado um sistema de automação residencial desenvolvido em ambiente real, no qual microcontroladores ESP32 são utilizados em conjunto com sensores, dispositivos inteligentes e a plataforma Home Assistant. Entre as aplicações desenvolvidas estão o monitoramento de condições ambientais, detecção do estado de portas e portões, controle de dispositivos e uma central com interface gráfica em tela sensível ao toque para monitoramento e interação com a residência. O projeto demonstra, na prática, como conceitos de sistemas embarcados, programação, redes de comunicação e Internet das Coisas podem ser integrados na construção de soluções de automação. A aplicação desenvolvida também evidencia a flexibilidade do ESP32 para projetos acadêmicos e aplicações cotidianas, permitindo que diferentes funcionalidades sejam incorporadas progressivamente ao sistema de acordo com as necessidades do usuário.',
      palavras:'ESP32; internet das coisas; sistemas embarcados; automação residencial; Home Assistant.'
    },
    {
      titulo:'AURA (Automated University Roll-Call and Attendance)',
      autores:['Heitor Santos Cortes','Paulo Henrique Amaral Martins','Bruno Gabriel Correa Pereira'],
      resumo:'O AURA (automated university roll-call and attendance) é um sistema web desenvolvido como trabalho de conclusão de curso com o objetivo de automatizar e tornar mais íntegro o controle de frequência acadêmica em instituições de ensino superior. A proposta surge da constatação de que métodos manuais de chamada são suscetíveis a erros e fraudes, e de que soluções alternativas já exploradas na literatura como o uso de QR Code estático ou de geolocalização isolada ainda deixam brechas para fraude, seja pelo compartilhamento do código entre alunos, seja pelo uso do dispositivo por terceiros dentro da área validada. Para superar essas limitações, o AURA combina duas camadas de verificação: um QR Code dinâmico rotativo, gerado por aula e com expiração de 30 segundos e validação por geolocalização, que confirma se o aluno está dentro de um raio de 100 metros da sala. O sistema oferece funcionalidades distintas para professores (cadastro de disciplinas e turmas, definição de frequência mínima, exibição do QR Code, acompanhamento em tempo real e alertas de risco) e para alunos (autocadastro, entrada em turmas por convite e registro de presença). É construído em Python/Django, com Django REST Framework, SQLite, e frontend em HTML/CSS.',
      palavras:'Frequência; QR Code; geolocalização; web; chamada; cadastro; validação.'
    },
    {
      titulo:'Gestão de finanças pessoais e empresariais com Python e Flask',
      autores:['Gabriel Eiji Nakandakari Shinkae','Mateus Yuri Koike','Edson Luiz Nogueira da Silva'],
      resumo:'A gestão financeira cotidiana, seja no âmbito doméstico ou na administração de micro e pequenas empresas, frequentemente representa uma atividade árdua e marcada por entraves operacionais recorrentes. Com o propósito claro de mitigar essas barreiras estruturais, o presente estudo apresenta o desenvolvimento prático de uma aplicação web voltada ao controle centralizado, ágil e intuitivo de receitas e despesas. O sistema foi rigorosamente estruturado com uma arquitetura modular robusta, utilizando a linguagem de programação Python juntamente com o framework Flask. O diferencial metodológico principal da ferramenta reside na integração bem-sucedida de recursos avançados voltados à eficiência operacional e à desburocratização de tarefas diárias. Para isso, a aplicação incorpora soluções baseadas em processamento de dados textuais e algoritmos de classificação supervisionada, viabilizando a categorização automática de lançamentos financeiros a partir de descrições simplificadas. Adicionalmente, implementou-se um mecanismo sofisticado de análise preditiva fundamentado em aprendizado de máquina, capaz de monitorar continuamente padrões de consumo e emitir prognósticos preventivos essenciais para a estabilidade do fluxo de caixa. Com suporte complementar à extração de dados de comprovantes por meio de reconhecimento óptico de caracteres e à rigorosa segregação lógica entre contas pessoais e corporativas, a solução atende com precisão às demandas contemporâneas de planejamento financeiro.',
      palavras:'Gestão financeira; aplicação web; Python; Flask.'
    },
    {
      titulo:'NovaOS: um sistema operacional com arquitetura híbrida',
      autores:['Guilherme Quintino dos Santos','Ana Clara Dias','Matheus Nascimento Alcaide','Gustavo Ferreira do Amaral','Muriel Vieira Teixeira'],
      resumo:'A escolha da arquitetura do kernel determina como um sistema operacional equilibra desempenho, segurança, estabilidade e capacidade de expansão. Este trabalho analisa qual arquitetura é mais adequada ao NovaOS, sistema pensado para computadores pessoais, que precisa executar navegador, aplicativos de escritório, jogos, comunicação, áudio e vídeo em um ambiente multitarefa complexo. Foram comparadas cinco arquiteturas: monolítica, em camadas, microkernel, modular e híbrida. A monolítica oferece alto desempenho, mas baixa segurança; o microkernel garante isolamento máximo, com sobrecarga de comunicação; a modular é flexível, porém sujeita a dependências circulares. A arquitetura híbrida foi adotada por combinar essas características: o kernel mantém um núcleo mínimo e de alta performance, responsável por processos, memória e escalonamento, enquanto serviços não críticos, como sistema de arquivos, áudio, vídeo e rede, executam em espaço de usuário. Em um cenário de falha grave no driver de áudio, o sistema monolítico pode travar por completo, ao passo que, no híbrido, apenas as aplicações de áudio são afetadas e o driver pode ser reiniciado. Como custos, destacam-se o overhead de comunicação entre kernel e serviços, a complexidade na gestão de dependências, o suporte a múltiplas APIs e a validação de cada chamada de sistema. Conclui-se que a arquitetura híbrida oferece o melhor equilíbrio para computadores pessoais, além de facilitar a manutenção e a evolução da plataforma sem recompilar o kernel.',
      palavras:'Kernel híbrido; sistemas operacionais; microkernel; espaço de usuário; isolamento de falhas.'
    },
    {
      titulo:'Gestão de transporte com confirmação de presença por QR Code e validação por geolocalização',
      autores:['Fabio Henrique Massucatto Sousa','Cristian César de Lima Filho','Richard Vieira do Espirito Santo'],
      resumo:'O controle de presença de trabalhadores e estudantes na região de Três Lagoas (MS), é majoritariamente realizado em listas de papel preenchidas manualmente, método sujeito a erros de preenchimento e extravio de documentos, dificultando a comprovação. Diante desse cenário, este trabalho propõe o desenvolvimento de um sistema web de gestão de transporte que permite o registro digital de presença por meio da leitura de um QR Code gerado dinamicamente pelo motorista, com validação automática por geolocalização. Ao embarcar, o passageiro lê o código pela câmera do celular e sua localização é comparada à do motorista, sendo valido o registro apenas em um raio de tolerância pré-definido, reduzindo o risco de fraudes. O sistema também permite o cadastro da localização residencial dos usuários, auxiliando o motorista na definição do trajeto de retorno por meio de um mapa com os pontos de embarque e desembarque previamente cadastrados. A solução é desenvolvida em Python com o microframework Flask, banco de dados SQLite, interface em HTML, CSS e JavaScript, biblioteca html5-qrcode para leitura do QR Code, Geolocation API para captura de coordenadas, Leaflet.js para exibição de mapas e a fórmula de Haversine para o cálculo de distâncias entre coordenadas geográficas. A validação experimental, conduzida em ambientes aberto, fechado e no interior do veículo, permite calibrar o raio de tolerância utilizado na validação da presença, reduzindo falhas técnicas do sistema proposto.',
      palavras:'QR Code; geolocalização; gestão de transporte; controle de presença; Geolocation API.'
    },
    {
      titulo:'Projeto Kaptika: gamificação como estratégia de aprendizagem',
      autores:['Felipe Yuji Shitara Shinkae','Erick da Costa Souza','Richard Vieira do Espirito Santo'],
      resumo:'O Kaptika é uma plataforma web gamificada desenvolvida para apoiar estudantes que se preparam para o Exame Nacional do Ensino Médio (ENEM). A proposta combina conteúdos e questões em atividades de curta duração com elementos de gamificação, buscando favorecer a regularidade dos estudos e fornecer feedback sobre o desempenho dos estudantes. A gamificação é compreendida como o uso de elementos de design de jogos em contextos que não são jogos. Estudos apontam resultados positivos em aspectos como motivação, engajamento e desempenho, embora seus efeitos dependam do contexto, do público e da forma como os elementos são projetados. Dessa forma, o Kaptika utiliza a gamificação como recurso de apoio à regularidade dos estudos, sem pressupor resultados automáticos. As mecânicas poderão incluir pontos de experiência (XP), níveis, sequência de dias de estudo (streak), metas e feedback de desempenho, priorizando aquelas viáveis para o produto mínimo viável. O projeto também incorpora o conceito de microlearning, caracterizado pela organização de conteúdos objetivos em pequenas unidades e períodos curtos de estudo. Pesquisas destacam a importância de objetivos claros e estrutura adequada para sua aplicação educacional. No Kaptika, o microlearning será aplicado principalmente na organização de sessões curtas de estudo e resolução de questões.',
      palavras:'Kaptika; gamificação; microlearning; ENEM; plataforma web; educação.'
    },
    {
      titulo:'Desenvolvimento de uma plataforma de incentivo à leitura baseada em gamificação e acompanhamento de progresso',
      autores:['Brenno Santiago dos Santos','João Victor de Souza Leme','Vinicius Duarte Tessari'],
      resumo:'A leitura constitui uma atividade relevante para o desenvolvimento cognitivo, a ampliação do conhecimento e a formação crítica dos indivíduos. Entretanto, a manutenção de uma rotina de leitura pode representar um desafio diante da crescente utilização de plataformas digitais e da disputa por atenção proporcionada por esses ambientes. Nesse contexto, a gamificação apresenta-se como uma estratégia capaz de incorporar elementos característicos dos jogos, como metas, acompanhamento de progresso, recompensas e mecanismos de interação, em atividades não relacionadas diretamente aos jogos. A formação e a manutenção de hábitos também podem ser favorecidas pela definição de objetivos e pelo acompanhamento contínuo das atividades realizadas. Diante disso, este trabalho tem como objetivo desenvolver uma plataforma mobile de incentivo à leitura baseada em gamificação e acompanhamento de progresso, adaptando mecanismos de engajamento presentes em plataformas digitais para um contexto produtivo e voltado ao desenvolvimento de hábitos de leitura. A aplicação proposta busca permitir o registro de livros, definição de metas de leitura, acompanhamento da evolução, registro das atividades realizadas, manutenção de sequências de leitura (streaks) e interação entre usuários. Dessa forma, busca-se proporcionar uma experiência que estimule a constância e o engajamento com a leitura, utilizando recursos tecnológicos como ferramentas de apoio à formação e manutenção desse hábito.',
      palavras:'Gamificação; leitura; aplicação móvel; engajamento; formação de hábitos.'
    }
  ]
};
