/* Mantém os mesmos botões e data-attributes; apenas os apresenta em menu. */
(function(){
  function closeAllMenus(except){document.querySelectorAll('.action-stack.action-menu.open').forEach(stack=>{if(stack===except)return;stack.classList.remove('open');stack.querySelector('.action-menu-trigger')?.setAttribute('aria-expanded','false');stack.__actionMenuPanel?.classList.remove('open')})}
  function positionPanel(trigger,panel){panel.classList.add('open');const rect=trigger.getBoundingClientRect(),panelRect=panel.getBoundingClientRect();let left=rect.right-panelRect.width;if(left<8)left=8;if(left+panelRect.width>window.innerWidth-8)left=window.innerWidth-8-panelRect.width;let top=rect.bottom+6;if(top+panelRect.height>window.innerHeight-8)top=rect.top-panelRect.height-6;panel.style.left=left+'px';panel.style.top=top+'px'}
  function menuify(stack){if(stack.dataset.menuified)return;const buttons=[...stack.children].filter(el=>el.tagName==='BUTTON');if(buttons.length<2)return;stack.dataset.menuified='1';stack.classList.add('action-menu');const trigger=document.createElement('button');trigger.type='button';trigger.className='mini action-menu-trigger';trigger.setAttribute('aria-label','Mais ações');trigger.setAttribute('aria-haspopup','true');trigger.setAttribute('aria-expanded','false');trigger.textContent='⋯';const panel=document.createElement('div');panel.className='action-menu-panel';panel.style.position='fixed';buttons.forEach(button=>{button.classList.add('action-menu-item');panel.appendChild(button);button.addEventListener('click',()=>{stack.classList.remove('open');trigger.setAttribute('aria-expanded','false');panel.classList.remove('open')})});trigger.addEventListener('click',event=>{event.stopPropagation();const opening=!stack.classList.contains('open');closeAllMenus(opening?stack:null);stack.classList.toggle('open',opening);trigger.setAttribute('aria-expanded',opening?'true':'false');if(opening)positionPanel(trigger,panel);else panel.classList.remove('open')});stack.appendChild(trigger);stack.__actionMenuPanel=panel;document.body.appendChild(panel)}
  const bindBeforeActionMenu=bind;bind=function(){bindBeforeActionMenu();document.querySelectorAll('.desktop-schedule .action-stack').forEach(menuify)};
  if(!window.__actionMenuGlobalBound){window.__actionMenuGlobalBound=true;document.addEventListener('click',event=>{if(event.target.closest('.action-menu-panel')||event.target.closest('.action-menu-trigger'))return;closeAllMenus()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeAllMenus()});window.addEventListener('scroll',()=>closeAllMenus(),true);window.addEventListener('resize',()=>closeAllMenus())}
  const renderBeforeActionMenu=render;render=function(){document.querySelectorAll('.action-menu-panel').forEach(panel=>panel.remove());renderBeforeActionMenu()};
})();
