(function(){
  'use strict';
  db.forms=db.forms||[];db.formResponses=db.formResponses||[];
  state.formSearch=state.formSearch||'';state.formCourse=state.formCourse||'Todos';state.formsModal=null;
  const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const isMissing=e=>/schema cache|does not exist|Could not find/i.test(e?.message||'');
  async function loadForms(){
    const fq=banco.from('formularios').select('*').order('criado_em',{ascending:false});
    const fr=await fq;if(fr.error){if(!isMissing(fr.error))console.error('Formulários:',fr.error);db.forms=[];return}
    db.forms=fr.data||[];
    if(state.role==='coord'){
      const rr=await banco.from('formulario_respostas').select('*,formulario_resposta_disciplinas(matriz_disciplina_id)').order('criado_em',{ascending:false});
      db.formResponses=rr.error?[]:(rr.data||[]).map(r=>({...r,disciplineIds:(r.formulario_resposta_disciplinas||[]).map(x=>+x.matriz_disciplina_id)}));
    }else db.formResponses=[];
    installVisibleEntries();
  }
  function activeForms(){return db.forms.filter(f=>f.ativo&&(f.cursos||[]).includes(state.course))}
  function formsIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h9l5 5v15H6V2Z"/><path d="M14 2v6h6M9 13h8M9 17h6"/></svg>'}
  function adminNavButton(){return '<button data-page="forms" class="'+(state.page==='forms'?'on':'')+'"><b class="nav-icon">'+formsIcon()+'</b>Formulários</button>'}
  const oldNav=nav;nav=function(){let x=oldNav();if(state.role!=='coord'||x.includes('data-page="forms"'))return x;return x.replace(/(?=<button data-page="maintenance")/,adminNavButton())};
  const oldTabs=portalTabs;portalTabs=function(){let x=oldTabs();if(!activeForms().length||x.includes('data-publictab="forms"'))return x;return x.replace(/<\/div>$/,'<button class="portal-tab '+(state.publicTab==='forms'?'on':'')+'" data-publictab="forms">Formulários</button></div>')};
  const oldPublicPage=publicPage;publicPage=function(){if(state.publicTab==='forms'&&['ADS','EDC'].includes(state.course))return publicLayout(portalHero()+portalTabs()+publicForms());return oldPublicPage()};
  const oldRender=render;render=function(){if(auth&&state.role==='coord'&&state.page==='forms'){document.getElementById('root').innerHTML=layout(formsAdmin(),'Formulários');bind();return}oldRender()};
  function installVisibleEntries(){
    if(state.role==='coord'){const n=document.querySelector('.nav');if(n&&!n.querySelector('[data-page="forms"]')){const maintenance=n.querySelector('[data-page="maintenance"]');maintenance?.insertAdjacentHTML('beforebegin',adminNavButton());bind()}}
    if(activeForms().length){const tabs=document.querySelector('.portal-tabs');if(tabs&&!tabs.querySelector('[data-publictab="forms"]')){tabs.insertAdjacentHTML('beforeend','<button class="portal-tab" data-publictab="forms">Formulários</button>');bind()}}
  }
  function adminModal(){if(!state.formsModal)return'';return '<div class="forms-modal"><section class="forms-modal-card"><div class="forms-modal-head"><h2>Novo formulário</h2><button class="mini" data-close-formmodal>×</button></div><div class="forms-modal-body"><label><b>Título</b><input id="form-title" maxlength="120" value="Formulário de dependências"></label><label><b>Categoria</b><select id="form-category"><option value="dependencias">Dependências</option></select></label><label><b>Orientações aos estudantes</b><textarea id="form-description" rows="4" maxlength="1200" placeholder="Explique o objetivo e como preencher."></textarea></label><div><b>Cursos</b><div class="forms-course-picks"><label><input type="checkbox" class="form-course" value="ADS" checked> ADS</label><label><input type="checkbox" class="form-course" value="EDC" checked> EDC</label></div></div><label><input type="checkbox" id="form-active"> Ativar e publicar imediatamente</label></div><div class="forms-modal-actions"><button class="btn ghost" data-close-formmodal>Cancelar</button><button class="btn primary" id="save-form-config">Cadastrar formulário</button></div></section></div>'}
  function formsAdmin(){
    const responses=db.formResponses||[],active=db.forms.filter(f=>f.ativo).length;
    let filtered=responses.filter(r=>(state.formCourse==='Todos'||r.curso===state.formCourse)&&(!state.formSearch||r.nome_estudante.toLowerCase().includes(state.formSearch.toLowerCase())));
    const cards=db.forms.length?db.forms.map(f=>'<article class="form-card '+(f.ativo?'active':'')+'"><div class="form-card-head"><div><span class="forms-badge">'+h(f.categoria==='dependencias'?'DEPENDÊNCIAS':f.categoria)+'</span><h3>'+h(f.titulo)+'</h3></div><span class="forms-badge '+(f.ativo?'active':'')+'">'+(f.ativo?'Público e ativo':'Não publicado')+'</span></div><p>'+h(f.descricao||'Sem orientações adicionais.')+'</p><div>'+(f.cursos||[]).map(c=>'<span class="course-tag">'+h(c)+'</span>').join(' ')+'</div><div class="form-card-actions"><button class="btn '+(f.ativo?'ghost':'primary')+'" data-toggle-form="'+f.id+'">'+(f.ativo?'Desativar':'Ativar formulário')+'</button>'+(!f.ativo?'<button class="btn danger" data-delete-form="'+f.id+'">Excluir</button>':'')+'</div></article>').join(''):'<div class="forms-empty">Nenhum formulário cadastrado.</div>';
    const rows=filtered.length?filtered.map(r=>{const deps=(r.disciplineIds||[]).map(id=>db.curriculum.find(d=>+d.id===+id)?.subject).filter(Boolean);return '<article class="response-card"><div class="response-student"><b>'+h(r.nome_estudante)+'</b><small>'+h(r.curso)+' · '+r.semestre_atual+'º semestre<br>'+new Date(r.criado_em).toLocaleDateString('pt-BR')+'</small></div><div class="dependency-list">'+(deps.length?deps.map(d=>'<span class="dependency-chip">'+h(d)+'</span>').join(''):'<span>Disciplinas não encontradas na matriz atual.</span>')+'</div><button class="mini" data-delete-response="'+r.id+'" title="Excluir resposta">Excluir</button></article>'}).join(''):'<div class="forms-empty">Nenhuma resposta encontrada.</div>';
    return '<div class="forms-page"><div class="forms-toolbar"><div><span class="eyebrow">ACOMPANHAMENTO ACADÊMICO</span><h1>Formulários</h1><p>Publique levantamentos e acompanhe as respostas sem expor dados entre estudantes.</p></div><button class="btn primary" data-new-form>+ Novo formulário</button></div><section class="forms-summary"><div class="forms-stat"><strong>'+db.forms.length+'</strong><span>formulário(s)</span></div><div class="forms-stat"><strong>'+active+'</strong><span>ativo(s) na área pública</span></div><div class="forms-stat"><strong>'+responses.length+'</strong><span>resposta(s) recebida(s)</span></div></section><section class="forms-config"><h2>Formulários cadastrados</h2><div class="forms-note">Ative somente o formulário que deve aparecer aos estudantes. As respostas permanecem visíveis apenas para a coordenação.</div><div class="forms-grid">'+cards+'</div></section><section class="forms-responses"><h2>Acompanhamento de dependências</h2><div class="forms-filters"><input id="form-response-search" placeholder="Pesquisar estudante" value="'+h(state.formSearch)+'"><select id="form-response-course"><option>Todos</option><option '+(state.formCourse==='ADS'?'selected':'')+'>ADS</option><option '+(state.formCourse==='EDC'?'selected':'')+'>EDC</option></select></div><div class="responses-list">'+rows+'</div></section></div>'+adminModal()}
  function publicForms(){const fs=activeForms();return '<section class="forms-public">'+(fs.length?fs.map(publicFormCard).join(''):'<div class="forms-empty">Nenhum formulário está disponível no momento.</div>')+'</section>'}
  function publicFormCard(f){const max=state.course==='ADS'?6:10,disc=db.curriculum.filter(d=>d.course===state.course).sort((a,b)=>a.semester-b.semester||a.subject.localeCompare(b.subject)),groups=[...new Set(disc.map(d=>d.semester))].map(s=>'<section class="matrix-semester"><h3>'+s+'º semestre da matriz</h3><div class="matrix-options">'+disc.filter(d=>d.semester===s).map(d=>'<label class="matrix-option"><input type="checkbox" name="dependency-'+f.id+'" value="'+d.id+'"><span>'+h(d.subject)+'</span></label>').join('')+'</div></section>').join('');return '<article class="public-form-card"><span class="forms-badge">DEPENDÊNCIAS</span><h2>'+h(f.titulo)+'</h2><p>'+h(f.descricao||'Informe as disciplinas em que você possui dependência para acompanhamento da coordenação.')+'</p><form class="dependency-form" data-dependency-form="'+f.id+'"><div class="form-row"><label><b>Nome completo</b><input name="student-name" maxlength="160" required autocomplete="name"></label><label><b>Semestre atual</b><select name="current-semester" required><option value="">Selecione</option>'+Array.from({length:max},(_,i)=>'<option value="'+(i+1)+'">'+(i+1)+'º semestre</option>').join('')+'</select></label></div><div><b>Disciplinas em dependência</b><p>Selecione uma ou mais disciplinas da matriz de '+state.course+'.</p><div class="matrix-groups">'+groups+'</div></div><div class="privacy-hint">As informações serão acessadas somente pela coordenação para acompanhamento acadêmico e não ficarão públicas.</div><button class="btn primary" type="submit">Enviar para a coordenação</button></form></article>'}
  async function saveConfig(){const title=document.getElementById('form-title')?.value.trim(),description=document.getElementById('form-description')?.value.trim(),courses=[...document.querySelectorAll('.form-course:checked')].map(x=>x.value);if(!title||!courses.length)return toast('Informe o título e ao menos um curso.');const b=document.getElementById('save-form-config');b.disabled=true;const {error}=await banco.from('formularios').insert({titulo:title,categoria:'dependencias',descricao:description||null,cursos,ativo:!!document.getElementById('form-active')?.checked,criado_por:state.teacherId||null});if(error){b.disabled=false;return toast('Não foi possível cadastrar: '+error.message)}state.formsModal=null;await loadForms();render();toast('Formulário cadastrado.')}
  async function toggleForm(id){const f=db.forms.find(x=>+x.id===+id);if(!f)return;const {error}=await banco.from('formularios').update({ativo:!f.ativo,atualizado_em:new Date().toISOString()}).eq('id',id);if(error)return toast('Não foi possível alterar: '+error.message);await loadForms();render();toast(f.ativo?'Formulário desativado.':'Formulário publicado.')}
  async function deleteForm(id){if(!confirm('Excluir este formulário e todas as respostas vinculadas?'))return;const {error}=await banco.from('formularios').delete().eq('id',id);if(error)return toast('Não foi possível excluir: '+error.message);await loadForms();render();toast('Formulário excluído.')}
  async function deleteResponse(id){if(!confirm('Excluir esta resposta do acompanhamento?'))return;const {error}=await banco.from('formulario_respostas').delete().eq('id',id);if(error)return toast('Não foi possível excluir: '+error.message);await loadForms();render();toast('Resposta excluída.')}
  async function submitDependencies(form){const id=+form.dataset.dependencyForm,name=form.elements['student-name'].value.trim(),semester=+form.elements['current-semester'].value,ids=[...form.querySelectorAll('input[type="checkbox"]:checked')].map(x=>+x.value);if(!name||!semester||!ids.length)return toast('Preencha o nome, o semestre atual e selecione ao menos uma disciplina.');const btn=form.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Enviando...';const {error}=await banco.rpc('enviar_formulario_dependencias',{p_formulario_id:id,p_nome_estudante:name,p_curso:state.course,p_semestre_atual:semester,p_disciplinas:ids});btn.disabled=false;btn.textContent='Enviar para a coordenação';if(error)return toast('Não foi possível enviar: '+error.message);form.reset();toast('Informações enviadas para a coordenação.')}
  const oldBind=bind;bind=function(){oldBind();document.querySelectorAll('[data-page="forms"]').forEach(b=>b.onclick=()=>{state.page='forms';render()});document.querySelectorAll('[data-publictab="forms"]').forEach(b=>b.onclick=()=>{state.publicTab='forms';render()});document.querySelector('[data-new-form]')?.addEventListener('click',()=>{state.formsModal=true;render()});document.querySelectorAll('[data-close-formmodal]').forEach(b=>b.onclick=()=>{state.formsModal=null;render()});document.getElementById('save-form-config')?.addEventListener('click',saveConfig);document.querySelectorAll('[data-toggle-form]').forEach(b=>b.onclick=()=>toggleForm(+b.dataset.toggleForm));document.querySelectorAll('[data-delete-form]').forEach(b=>b.onclick=()=>deleteForm(+b.dataset.deleteForm));document.querySelectorAll('[data-delete-response]').forEach(b=>b.onclick=()=>deleteResponse(+b.dataset.deleteResponse));document.getElementById('form-response-search')?.addEventListener('change',e=>{state.formSearch=e.target.value;render()});document.getElementById('form-response-course')?.addEventListener('change',e=>{state.formCourse=e.target.value;render()});document.querySelectorAll('[data-dependency-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();submitDependencies(f)})};
  const oldLoadData=loadData;loadData=async function(){await oldLoadData();await loadForms()};
  setTimeout(()=>loadForms().catch(console.error),700);
})();
