(function(){
  function esc(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
  const previousLoadData=loadData;
  loadData=async function(){
    await previousLoadData();
    if(state.role!=='coord')return;
    const [config,inscricoes]=await Promise.all([
      banco.from('inovatec_configuracoes').select('*').eq('id',1).maybeSingle(),
      banco.from('inovatec_inscricoes').select('*,inovatec_participantes(*)').order('criado_em',{ascending:false})
    ]);
    if(config.error){console.warn('Módulo INOVATEC indisponível:',config.error.message);db.inovatecConfig=null;db.inovatecInscricoes=[];return}
    db.inovatecConfig={abertas:!!config.data?.inscricoes_abertas,max:config.data?.max_participantes||4,prazo:config.data?.prazo_final||''};
    db.inovatecInscricoes=inscricoes.error?[]:(inscricoes.data||[]).map(item=>({...item,participantes:(item.inovatec_participantes||[]).sort((a,b)=>a.ordem-b.ordem)}));
  };
  const previousNav=nav;
  nav=function(){let html=previousNav();if(state.role==='coord'){const button='<button data-page="inovatec" class="'+(state.page==='inovatec'?'on':'')+'"><b class="nav-icon">'+navIcon('exams')+'</b>INOVATEC</button>';html=html.replace('<button data-page="requirements"',button+'<button data-page="requirements"')}return html};
  const previousRender=render;
  render=function(){if(auth&&state.role==='coord'&&state.page==='inovatec'){document.getElementById('root').innerHTML=page();bind();return}previousRender()};
  const previousBind=bind;
  bind=function(){previousBind();const title=document.querySelector('.inovatec-admin-config .cardhead h2');if(title)title.textContent='INOVATEC Showcase';document.getElementById('save-inovatec')?.addEventListener('click',saveConfig);document.querySelectorAll('[data-inovatec-status]').forEach(select=>select.addEventListener('change',()=>setStatus(select.dataset.inovatecStatus,select.value)))};
  function people(items){return '<ul class="inovatec-people">'+items.map(p=>'<li><b>'+esc(p.nome)+'</b><small>'+esc(p.email)+' · '+esc(p.whatsapp)+'</small></li>').join('')+'</ul>'}
  function row(item){const options=['recebida','confirmada','cancelada'].map(status=>'<option value="'+status+'" '+(item.status===status?'selected':'')+'>'+({recebida:'Recebida',confirmada:'Confirmada',cancelada:'Cancelada'}[status])+'</option>').join('');return '<tr><td><div class="inovatec-detail"><b>'+esc(item.titulo)+'</b><br><small>'+esc(item.curso)+' · '+esc(item.categoria)+'</small><p>'+esc(item.resumo)+'</p>'+(item.link?'<a href="'+esc(item.link)+'" target="_blank" rel="noopener">Abrir link ↗</a>':'')+'<div class="inovatec-format-list">'+(item.formatos||[]).map(f=>'<span>'+esc(f)+'</span>').join('')+'</div>'+(item.necessidades?'<p><b>Necessidades:</b> '+esc(item.necessidades)+'</p>':'')+'</div></td><td>'+people(item.participantes)+'</td><td>'+new Date(item.criado_em).toLocaleDateString('pt-BR')+'</td><td><select data-inovatec-status="'+item.id+'">'+options+'</select></td></tr>'}
  function page(){const config=db.inovatecConfig||{abertas:false,max:4,prazo:''},items=db.inovatecInscricoes||[],configCard='<div class="card inovatec-admin-config"><div class="cardhead"><div><h2>INOVATEC Showcase</h2><small>Controle o formulário público em tadsedc.site/inovatec</small></div><span class="badge '+(config.abertas?'':'pending')+'">'+(config.abertas?'Inscrições abertas':'Inscrições fechadas')+'</span></div><div class="inovatec-admin-body"><label class="inovatec-admin-switch"><span><b>Receber inscrições</b><small>Disponibiliza o formulário público para os estudantes.</small></span><input type="checkbox" id="inovatec-abertas" '+(config.abertas?'checked':'')+'></label><div class="inovatec-admin-settings"><div class="field"><label>Máximo de participantes</label><input id="inovatec-max" type="number" min="1" max="4" value="'+config.max+'"></div><div class="field"><label>Prazo final (opcional)</label><input id="inovatec-prazo" type="date" value="'+esc(config.prazo)+'"></div></div><div class="inovatec-admin-save"><button class="btn primary" id="save-inovatec">Salvar configuração</button></div></div></div>',list='<div class="card"><div class="cardhead"><div><h2>Inscrições recebidas</h2><small>'+items.length+' proposta(s)</small></div></div><div class="table"><table><thead><tr><th>Proposta</th><th>Participantes</th><th>Envio</th><th>Status</th></tr></thead><tbody>'+(items.length?items.map(row).join(''):'<tr><td colspan="4"><div class="empty">Nenhuma inscrição recebida ainda.</div></td></tr>')+'</tbody></table></div></div>';return layout(head('Semana Acadêmica','INOVATEC','Gerencie as atividades e inscrições da Semana Acadêmica.')+configCard+list,'INOVATEC')}
  async function saveConfig(){const button=document.getElementById('save-inovatec'),abertas=document.getElementById('inovatec-abertas').checked,max=Number(document.getElementById('inovatec-max').value),prazo=document.getElementById('inovatec-prazo').value||null;if(max<1||max>4)return toast('O grupo pode ter de 1 a 4 participantes.');button.disabled=true;button.textContent='Salvando…';try{const {error}=await banco.from('inovatec_configuracoes').update({inscricoes_abertas:abertas,max_participantes:max,prazo_final:prazo,atualizado_em:new Date().toISOString()}).eq('id',1);if(error)throw error;await loadData();render();toast('Configuração do INOVATEC atualizada.')}catch(error){console.error(error);toast('Não foi possível salvar: '+error.message)}finally{if(document.getElementById('save-inovatec')){button.disabled=false;button.textContent='Salvar configuração'}}}
  async function setStatus(id,status){try{const {error}=await banco.from('inovatec_inscricoes').update({status}).eq('id',id);if(error)throw error;await loadData();render();toast('Status da inscrição atualizado.')}catch(error){console.error(error);toast('Não foi possível atualizar: '+error.message)}}
})();
