/* Atendimento ao estudante: usa a estrutura de aulas, sem vínculo com turmas. */
(()=>{
  const CODE='ATENDIMENTO',isAttendance=item=>String(item?.code||'').toUpperCase()===CODE;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const owner=()=>db.teachers.find(item=>String(item.id)===String(auth))||{id:auth,name:state.userName||'Coordenação do Curso'};
  const roomOptions=selected=>'<option value="">Sem local definido</option>'+db.rooms.map(room=>'<option value="'+room.id+'" '+(String(selected||'')===String(room.id)?'selected':'')+'>'+esc(room.name)+' — '+esc(room.building)+', '+esc(room.floor)+'</option>').join('');
  function attendanceModal(item){const editing=Boolean(item),person=owner(),courses=item?.courses||['ADS','EDC'];return '<div class="modalbg" data-close><div class="modal attendance-modal" onclick="event.stopPropagation()"><div class="modaltop"><div><h2>'+(editing?'Editar atendimento':'Novo atendimento ao estudante')+'</h2><p>O aviso aparecerá antes das aulas, sem vínculo com turmas.</p></div><button class="close" data-close>×</button></div><div class="attendance-owner"><small>Responsável</small><strong>'+esc(person.name)+'</strong></div><div class="field"><label>Título do atendimento</label><input id="attendance-title" value="'+esc(item?.subject||'ATENDIMENTO AO ESTUDANTE')+'" maxlength="100"></div><div class="field"><label>Curso(s)</label><div class="course-picks"><label class="course-pick"><input id="attendance-ads" type="checkbox" '+(courses.includes('ADS')?'checked':'')+'> ADS</label><label class="course-pick"><input id="attendance-edc" type="checkbox" '+(courses.includes('EDC')?'checked':'')+'> EDC</label></div></div><div class="field"><label>'+(editing?'Dia da semana':'Dia(s) da semana')+'</label><div class="attendance-days">'+[1,2,3,4,5,6].map(day=>'<label class="attendance-day"><input type="checkbox" class="attendance-day-opt" value="'+day+'" '+(Number(item?.day)===day||(!editing&&day===1)?'checked':'')+'> '+dayNames[day]+'</label>').join('')+'</div></div><div class="two"><div class="field"><label>Horário inicial</label><input id="attendance-start" type="time" value="'+esc(item?.start||'17:30')+'"></div><div class="field"><label>Horário final</label><input id="attendance-end" type="time" value="'+esc(item?.end||'18:30')+'"></div></div><div class="field"><label>Local (opcional)</label><select id="attendance-room">'+roomOptions(item?.roomId)+'</select></div><div class="actions"><button class="btn soft" data-close>Cancelar</button><button class="btn primary attendance-action" id="saveattendance" data-id="'+esc(item?.id||'')+'">'+(editing?'Salvar alterações':'Cadastrar atendimento')+'</button></div></div></div>'}
  async function saveAttendance(id){if(state.role!=='coord')return toast('Somente a coordenação pode cadastrar atendimentos.');const title=(document.getElementById('attendance-title')?.value||'').trim().toUpperCase(),days=[...document.querySelectorAll('.attendance-day-opt:checked')].map(input=>Number(input.value)),start=document.getElementById('attendance-start')?.value,end=document.getElementById('attendance-end')?.value,roomValue=document.getElementById('attendance-room')?.value,courses=[];if(document.getElementById('attendance-ads')?.checked)courses.push('ADS');if(document.getElementById('attendance-edc')?.checked)courses.push('EDC');if(!title||!days.length||!start||!end||!courses.length)return toast('Informe título, curso, dia e horários do atendimento.');if(start>=end)return toast('O horário final deve ser posterior ao horário inicial.');const person=owner(),payload=day=>({codigo:CODE,disciplina:title,professor_id:person.id,professor_nome:person.name,turma_id:null,cursos:courses,dia_semana:day,inicio:start,fim:end,sala_padrao_id:roomValue?Number(roomValue):null,ativa:true});try{if(id){const {error}=await banco.from('aulas').update(payload(days[0])).eq('id',id);if(error)throw error}else{const {error}=await banco.from('aulas').insert(days.map(payload));if(error)throw error}await loadData();state.modal=null;render();toast(id?'Atendimento atualizado.':'Atendimento cadastrado em '+days.length+' dia(s).')}catch(error){console.error(error);toast('Não foi possível salvar o atendimento: '+error.message)}}
  const priorList=list;list=function(all=false){return priorList(all).sort((a,b)=>Number(isAttendance(b))-Number(isAttendance(a))||a.day-b.day||a.start.localeCompare(b.start))};
  const priorTable=table;table=function(rows,edit=true,day=false){const html=priorTable(rows,edit,day);if(!rows.some(isAttendance))return html;const root=document.createElement('div');root.innerHTML=html;rows.filter(isAttendance).forEach(item=>{root.querySelectorAll('.desktop-schedule tbody tr').forEach(row=>{if(row.querySelector('.discipline b')?.textContent.trim()!==item.subject||!row.textContent.includes(CODE))return;row.classList.add('attendance-card');const status=row.querySelector('.status'),location=row.querySelector('.badge');if(status){status.classList.remove('pending');status.textContent='Atendimento'}if(location?.textContent.includes('Sala não definida')){location.classList.remove('pending');location.textContent='Local ainda não informado'}});root.querySelectorAll('.mobile-schedule .schedule-card').forEach(card=>{const title=card.querySelector('h3');if(title?.textContent.trim()!==item.subject||!card.textContent.includes(CODE))return;card.classList.add('attendance-card');title.insertAdjacentHTML('afterend','<span class="attendance-label">Atendimento da coordenação</span>');const status=card.querySelector('.status');if(status){status.classList.remove('pending');status.textContent='Atendimento'}const location=card.querySelector('.roomline b');if(location?.textContent.includes('Sala não definida'))location.textContent='Local ainda não informado'})});return root.innerHTML};
  const addButton=html=>state.role==='coord'?html.replace(/(<button class="btn primary" data-newclass>[^<]*Nova aula<\/button>)/,'<button class="btn attendance-action" data-newattendance>＋ Atendimento</button>$1'):html;
  const priorDash=dash;dash=function(){return addButton(priorDash())};const priorClasses=classes;classes=function(){return addButton(priorClasses())};
  const priorModal=modal;modal=function(){if(state.modal?.type==='attendance')return attendanceModal();if(state.modal?.type==='editclass'){const item=db.classes.find(row=>String(row.id)===String(state.modal.id));if(isAttendance(item))return attendanceModal(item)}return priorModal()};
  const priorBind=bind;bind=function(){priorBind();document.querySelectorAll('[data-newattendance]').forEach(button=>button.onclick=()=>{state.modal={type:'attendance'};render()});document.getElementById('saveattendance')?.addEventListener('click',event=>saveAttendance(event.currentTarget.dataset.id))};
})();
