-- Cobertura docente eventual por aula, com identificação interna restrita.

create table if not exists public.professor_substituicoes (
  id bigint generated by default as identity primary key,
  aula_id bigint not null references public.aulas(id) on delete cascade,
  professor_substituto_id uuid not null references public.perfis(id) on delete cascade,
  professor_substituto_nome text not null default '',
  professor_titular_id uuid references public.perfis(id) on delete set null,
  professor_titular_nome text not null default '',
  inicio date not null,
  fim date not null,
  observacoes text,
  ativo boolean not null default true,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint professor_substituicoes_periodo_valido check (fim >= inicio),
  constraint professor_substituicoes_docentes_distintos check (
    professor_titular_id is null or professor_titular_id <> professor_substituto_id
  )
);

create index if not exists professor_substituicoes_aula_idx
  on public.professor_substituicoes (aula_id, inicio, fim);
create index if not exists professor_substituicoes_professor_idx
  on public.professor_substituicoes (professor_substituto_id, inicio, fim);

create or replace function public.preparar_cobertura_docente()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  aula_atual record;
  substituto_atual record;
begin
  if not public.usuario_e_coordenador() then
    raise exception 'Acesso exclusivo da coordenação';
  end if;

  select a.professor_id, a.professor_nome
    into aula_atual
  from public.aulas a
  where a.id = new.aula_id;

  if not found then
    raise exception 'Aula não encontrada';
  end if;

  select p.id, p.nome
    into substituto_atual
  from public.perfis p
  where p.id = new.professor_substituto_id
    and p.papel = 'professor'
    and p.ativo = true;

  if not found then
    raise exception 'Professor eventual não encontrado ou sem acesso ativo';
  end if;

  if aula_atual.professor_id = substituto_atual.id then
    raise exception 'O professor eventual deve ser diferente do titular';
  end if;

  if exists (
    select 1
    from public.professor_substituicoes x
    where x.aula_id = new.aula_id
      and x.ativo = true
      and x.id <> coalesce(new.id, 0)
      and daterange(x.inicio, x.fim, '[]') && daterange(new.inicio, new.fim, '[]')
  ) then
    raise exception 'Já existe uma cobertura nesta aula durante o período informado';
  end if;

  new.professor_substituto_nome := substituto_atual.nome;
  new.professor_titular_id := aula_atual.professor_id;
  new.professor_titular_nome := aula_atual.professor_nome;
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists preparar_cobertura_docente
  on public.professor_substituicoes;
create trigger preparar_cobertura_docente
before insert or update on public.professor_substituicoes
for each row execute function public.preparar_cobertura_docente();

alter table public.professor_substituicoes enable row level security;

drop policy if exists "Coordenacao gerencia coberturas docentes"
  on public.professor_substituicoes;
create policy "Coordenacao gerencia coberturas docentes"
on public.professor_substituicoes for all to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

drop policy if exists "Professor consulta suas coberturas"
  on public.professor_substituicoes;
create policy "Professor consulta suas coberturas"
on public.professor_substituicoes for select to authenticated
using (professor_substituto_id = auth.uid());

revoke all on public.professor_substituicoes from anon;
grant select, insert, update, delete on public.professor_substituicoes to authenticated;
grant usage, select on sequence public.professor_substituicoes_id_seq to authenticated;

create or replace function public.professor_cobre_aula(p_aula_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.professor_substituicoes x
    join public.perfis p on p.id = x.professor_substituto_id
    where x.aula_id = p_aula_id
      and x.professor_substituto_id = auth.uid()
      and x.ativo = true
      and p.ativo = true
      and current_date between x.inicio and x.fim
  );
$$;

revoke all on function public.professor_cobre_aula(bigint) from public;
grant execute on function public.professor_cobre_aula(bigint) to authenticated;

-- A visão pública revela apenas quem ministra a aula no período atual.
-- Nenhuma informação de titularidade ou substituição é exposta.
create or replace view public.aulas_professores_atuais
with (security_barrier = true)
as
select distinct on (x.aula_id)
  x.aula_id,
  x.professor_substituto_id as professor_id,
  x.professor_substituto_nome as professor_nome
from public.professor_substituicoes x
join public.perfis p on p.id = x.professor_substituto_id
where x.ativo = true
  and p.ativo = true
  and current_date between x.inicio and x.fim
order by x.aula_id, x.inicio desc, x.id desc;

revoke all on public.aulas_professores_atuais from public;
grant select on public.aulas_professores_atuais to anon, authenticated;

-- Permite ao professor eventual alterar somente aulas cobertas durante a vigência.
drop policy if exists "Professor eventual altera aula coberta" on public.aulas;
create policy "Professor eventual altera aula coberta"
on public.aulas for update to authenticated
using (public.professor_cobre_aula(id))
with check (public.professor_cobre_aula(id));

drop policy if exists "Professor eventual atualiza sala da aula" on public.salas_do_dia;
create policy "Professor eventual atualiza sala da aula"
on public.salas_do_dia for all to authenticated
using (public.professor_cobre_aula(aula_id))
with check (public.professor_cobre_aula(aula_id));

-- Registra no histórico quando o professor eventual altera a sala.
create or replace function public.registrar_historico_alteracao_sala()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.sala_padrao_id is distinct from old.sala_padrao_id
     and exists (
       select 1 from public.perfis p
       where p.id = auth.uid()
         and p.papel = 'professor'
         and p.ativo = true
     )
     and (
       new.professor_id = auth.uid()
       or public.professor_cobre_aula(new.id)
     )
  then
    insert into public.historico_alteracoes_sala
      (professor_id, aula_id, sala_id)
    values
      (auth.uid(), new.id, new.sala_padrao_id);
  end if;
  return new;
end;
$$;

notify pgrst, 'reload schema';
