-- Materiais e links dos professores organizados por disciplina.
-- Execute no SQL Editor do Supabase antes de usar a nova funcionalidade.

begin;

create table if not exists public.professor_materiais (
  id bigint generated by default as identity primary key,
  professor_id uuid not null references public.perfis(id) on delete cascade,
  matriz_disciplina_id bigint references public.matriz_disciplinas(id) on delete set null,
  turma_id bigint references public.turmas(id) on delete set null,
  disciplina text not null,
  cursos text[] not null default array[]::text[],
  tipo text not null check (tipo in ('Google Classroom', 'GitHub', 'GrupoAU', 'Outro')),
  titulo text not null,
  url text not null check (url ~* '^https?://'),
  ativo boolean not null default true,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists professor_materiais_professor_idx
  on public.professor_materiais (professor_id);

create index if not exists professor_materiais_disciplina_idx
  on public.professor_materiais (disciplina);

create index if not exists professor_materiais_turma_idx
  on public.professor_materiais (turma_id);

alter table public.professor_materiais enable row level security;

drop policy if exists "Materiais ativos sao publicos" on public.professor_materiais;
create policy "Materiais ativos sao publicos"
  on public.professor_materiais
  for select
  to anon, authenticated
  using (ativo = true);

drop policy if exists "Coordenacao gerencia materiais docentes" on public.professor_materiais;
create policy "Coordenacao gerencia materiais docentes"
  on public.professor_materiais
  for all
  to authenticated
  using (public.e_coordenador())
  with check (public.e_coordenador());

drop policy if exists "Professor cadastra seus materiais" on public.professor_materiais;
create policy "Professor cadastra seus materiais"
  on public.professor_materiais
  for insert
  to authenticated
  with check (professor_id = auth.uid());

drop policy if exists "Professor atualiza seus materiais" on public.professor_materiais;
create policy "Professor atualiza seus materiais"
  on public.professor_materiais
  for update
  to authenticated
  using (professor_id = auth.uid())
  with check (professor_id = auth.uid());

drop policy if exists "Professor exclui seus materiais" on public.professor_materiais;
create policy "Professor exclui seus materiais"
  on public.professor_materiais
  for delete
  to authenticated
  using (professor_id = auth.uid());

grant select on public.professor_materiais to anon, authenticated;
grant insert, update, delete on public.professor_materiais to authenticated;
grant usage, select on sequence public.professor_materiais_id_seq to authenticated;

-- Garante que as disciplinas ativas da matriz estejam disponíveis nos
-- formulários públicos e autenticados, sem liberar edição anônima.
alter table public.matriz_disciplinas enable row level security;

drop policy if exists "Matriz ativa publica para materiais"
  on public.matriz_disciplinas;
create policy "Matriz ativa publica para materiais"
  on public.matriz_disciplinas
  for select
  to anon, authenticated
  using (ativa = true);

grant select on public.matriz_disciplinas to anon, authenticated;

-- Sincroniza automaticamente o tipo do link com "Materiais de aula" do
-- perfil. O professor só pode alterar o próprio perfil; a coordenação
-- pode sincronizar qualquer docente.
create or replace function public.sincronizar_material_professor(
  professor_alvo uuid,
  material_novo text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null
     or (
       auth.uid() <> professor_alvo
       and not public.e_coordenador()
     ) then
    raise exception 'Sem permissão para atualizar os materiais deste professor';
  end if;

  if material_novo not in ('Google Classroom', 'GitHub', 'GrupoAU') then
    return;
  end if;

  update public.perfis
     set materiais = array(
       select distinct valor
       from unnest(
         coalesce(materiais, array[]::text[])
         || array[material_novo]
       ) as itens(valor)
     )
   where id = professor_alvo
     and ativo = true;
end;
$$;

revoke all on function public.sincronizar_material_professor(uuid, text)
  from public;
grant execute on function public.sincronizar_material_professor(uuid, text)
  to authenticated;

commit;

-- Solicita ao PostgREST a atualização imediata do cache do esquema.
notify pgrst, 'reload schema';

select
  tablename,
  policyname,
  roles,
  cmd
from pg_policies
where schemaname = 'public'
  and tablename = 'professor_materiais'
order by policyname;
