-- Módulo genérico de controle de presença.
--
-- Serve para QUALQUER atividade que precise confirmar presença (Semana
-- Acadêmica, apresentações on-line do ECEAEMS, palestras, etc.): a
-- coordenação cadastra a atividade, decide se quer capturar a localização
-- do celular (faz sentido para atividade presencial, não faz sentido para
-- uma atividade on-line) e, na hora, "libera" um código/QR válido só por
-- alguns minutos. O estudante escaneia o QR (ou digita o código) em
-- tadsedc.site/presenca, se identifica (nome, RA, curso) e confirma.
--
-- Mesmo padrão já usado no ECEAEMS e no formulário de dependências: o
-- público nunca insere direto nas tabelas — só existem duas funções
-- "security definer" (verificar_codigo_presenca e registrar_presenca) que
-- validam tudo no banco antes de gravar.

-- ==========================================================================
-- 1. Atividades
-- ==========================================================================

create table if not exists public.presenca_atividades (
  id bigint generated by default as identity primary key,
  titulo text not null,
  categoria text,
  data date,
  local text,
  capturar_geolocalizacao boolean not null default true,
  ativa boolean not null default true,
  criado_em timestamptz not null default now(),
  constraint presenca_atividades_titulo_tamanho
    check (char_length(trim(titulo)) between 3 and 200)
);

-- ==========================================================================
-- 2. Liberações (janelas de tempo em que um código fica válido)
-- ==========================================================================

create table if not exists public.presenca_liberacoes (
  id bigint generated by default as identity primary key,
  atividade_id bigint not null references public.presenca_atividades(id) on delete cascade,
  codigo text not null,
  criado_em timestamptz not null default now(),
  expira_em timestamptz not null,
  encerrada_em timestamptz,
  constraint presenca_liberacoes_codigo_formato
    check (codigo ~ '^[A-Z0-9]{6,10}$')
);

create unique index if not exists presenca_liberacoes_codigo_unico
  on public.presenca_liberacoes (codigo);

create index if not exists presenca_liberacoes_atividade_idx
  on public.presenca_liberacoes (atividade_id, criado_em desc);

-- ==========================================================================
-- 3. Registros de presença (os check-ins)
-- ==========================================================================

create table if not exists public.presenca_registros (
  id bigint generated by default as identity primary key,
  atividade_id bigint not null references public.presenca_atividades(id) on delete cascade,
  liberacao_id bigint not null references public.presenca_liberacoes(id) on delete cascade,
  nome text not null,
  ra text not null,
  ra_normalizado text generated always as (lower(regexp_replace(ra, '\s+', '', 'g'))) stored,
  curso text not null,
  latitude double precision,
  longitude double precision,
  precisao_metros double precision,
  user_agent text,
  criado_em timestamptz not null default now(),
  constraint presenca_registros_nome_tamanho
    check (char_length(trim(nome)) between 3 and 160),
  constraint presenca_registros_ra_tamanho
    check (char_length(trim(ra)) between 1 and 30),
  constraint presenca_registros_curso_valido check (curso in ('ADS', 'EDC')),
  constraint presenca_registros_atividade_ra_unico
    unique (atividade_id, ra_normalizado)
);

create index if not exists presenca_registros_atividade_idx
  on public.presenca_registros (atividade_id, criado_em desc);

alter table public.presenca_atividades enable row level security;
alter table public.presenca_liberacoes enable row level security;
alter table public.presenca_registros enable row level security;

-- Só a coordenação lê/edita/apaga essas três tabelas diretamente. O público
-- nunca tem select/insert/update/delete aqui — tudo passa pelas funções
-- abaixo, que já devolvem só o estritamente necessário para o check-in.
drop policy if exists "Coordenacao gerencia atividades de presenca"
  on public.presenca_atividades;
create policy "Coordenacao gerencia atividades de presenca"
on public.presenca_atividades for all
to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

drop policy if exists "Coordenacao gerencia liberacoes de presenca"
  on public.presenca_liberacoes;
create policy "Coordenacao gerencia liberacoes de presenca"
on public.presenca_liberacoes for all
to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

drop policy if exists "Coordenacao gerencia registros de presenca"
  on public.presenca_registros;
create policy "Coordenacao gerencia registros de presenca"
on public.presenca_registros for all
to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

revoke all on public.presenca_atividades from anon;
revoke all on public.presenca_liberacoes from anon;
revoke all on public.presenca_registros from anon;
grant select, insert, update, delete on public.presenca_atividades to authenticated;
grant select, insert, update, delete on public.presenca_liberacoes to authenticated;
grant select, insert, update, delete on public.presenca_registros to authenticated;
grant usage, select on sequence public.presenca_atividades_id_seq to authenticated;
grant usage, select on sequence public.presenca_liberacoes_id_seq to authenticated;
grant usage, select on sequence public.presenca_registros_id_seq to authenticated;

-- ==========================================================================
-- 4. Função pública: conferir se um código ainda é válido
-- ==========================================================================
--
-- Chamada assim que a página tadsedc.site/presenca abre com ?codigo=XXXX
-- (ou quando o estudante digita o código manualmente). Nunca dá erro — só
-- devolve {"valido": false, "mensagem": "..."} quando o código não existe,
-- expirou ou foi encerrado, para a página mostrar uma mensagem amigável.

create or replace function public.verificar_codigo_presenca(p_codigo text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo text := upper(trim(coalesce(p_codigo, '')));
  v_liberacao record;
begin
  if v_codigo = '' then
    return jsonb_build_object('valido', false, 'mensagem', 'Código não informado.');
  end if;

  select l.id, l.atividade_id, l.expira_em, l.encerrada_em,
         a.titulo, a.categoria, a.capturar_geolocalizacao, a.ativa
    into v_liberacao
  from public.presenca_liberacoes l
  join public.presenca_atividades a on a.id = l.atividade_id
  where l.codigo = v_codigo;

  if not found then
    return jsonb_build_object('valido', false, 'mensagem', 'Código inválido. Confira o código ou peça um novo à coordenação.');
  end if;

  if not v_liberacao.ativa then
    return jsonb_build_object('valido', false, 'mensagem', 'Esta atividade não está mais disponível para check-in.');
  end if;

  if v_liberacao.encerrada_em is not null then
    return jsonb_build_object('valido', false, 'mensagem', 'O check-in desta atividade foi encerrado pela coordenação.');
  end if;

  if v_liberacao.expira_em <= now() then
    return jsonb_build_object('valido', false, 'mensagem', 'Este código expirou. Peça um novo à coordenação.');
  end if;

  return jsonb_build_object(
    'valido', true,
    'atividade_id', v_liberacao.atividade_id,
    'titulo', v_liberacao.titulo,
    'categoria', v_liberacao.categoria,
    'capturar_geolocalizacao', v_liberacao.capturar_geolocalizacao
  );
end;
$$;

revoke all on function public.verificar_codigo_presenca(text) from public;
grant execute on function public.verificar_codigo_presenca(text) to anon, authenticated;

-- ==========================================================================
-- 5. Função pública: registrar a presença
-- ==========================================================================

create or replace function public.registrar_presenca(
  p_codigo text,
  p_nome text,
  p_ra text,
  p_curso text,
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_precisao double precision default null,
  p_user_agent text default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo text := upper(trim(coalesce(p_codigo, '')));
  v_liberacao record;
  v_registro_id bigint;
begin
  select l.id, l.atividade_id, l.expira_em, l.encerrada_em,
         a.capturar_geolocalizacao, a.ativa
    into v_liberacao
  from public.presenca_liberacoes l
  join public.presenca_atividades a on a.id = l.atividade_id
  where l.codigo = v_codigo;

  if not found or not v_liberacao.ativa then
    raise exception 'Código inválido. Confira o código ou peça um novo à coordenação.';
  end if;

  if v_liberacao.encerrada_em is not null then
    raise exception 'O check-in desta atividade foi encerrado pela coordenação.';
  end if;

  if v_liberacao.expira_em <= now() then
    raise exception 'Este código expirou. Peça um novo à coordenação.';
  end if;

  if char_length(trim(coalesce(p_nome, ''))) not between 3 and 160 then
    raise exception 'Informe o nome completo.';
  end if;

  if char_length(trim(coalesce(p_ra, ''))) < 1 then
    raise exception 'Informe a matrícula (RA).';
  end if;

  if p_curso not in ('ADS', 'EDC') then
    raise exception 'Selecione o curso.';
  end if;

  begin
    insert into public.presenca_registros
      (atividade_id, liberacao_id, nome, ra, curso, latitude, longitude, precisao_metros, user_agent)
    values (
      v_liberacao.atividade_id,
      v_liberacao.id,
      trim(p_nome),
      trim(p_ra),
      p_curso,
      case when v_liberacao.capturar_geolocalizacao then p_latitude else null end,
      case when v_liberacao.capturar_geolocalizacao then p_longitude else null end,
      case when v_liberacao.capturar_geolocalizacao then p_precisao else null end,
      p_user_agent
    )
    returning id into v_registro_id;
  exception
    when unique_violation then
      raise exception 'Este RA já registrou presença nesta atividade.';
  end;

  return v_registro_id;
end;
$$;

revoke all on function public.registrar_presenca(text, text, text, text, double precision, double precision, double precision, text) from public;
grant execute on function public.registrar_presenca(text, text, text, text, double precision, double precision, double precision, text) to anon, authenticated;

notify pgrst, 'reload schema';
