-- INOVATEC Showcase — inscrições públicas e gestão pela coordenação.

create table if not exists public.inovatec_configuracoes (
  id smallint primary key default 1,
  inscricoes_abertas boolean not null default false,
  max_participantes smallint not null default 4 check (max_participantes between 1 and 4),
  prazo_final date,
  atualizado_em timestamptz not null default now(),
  constraint inovatec_configuracoes_singleton check (id = 1)
);

insert into public.inovatec_configuracoes (id) values (1) on conflict (id) do nothing;

create table if not exists public.inovatec_inscricoes (
  id bigint generated by default as identity primary key,
  titulo text not null check (char_length(trim(titulo)) between 3 and 180),
  curso text not null check (curso in ('ADS','EDC','OUTRO')),
  categoria text not null check (categoria in ('Sistemas web','Aplicativos','Jogos','Projetos de redes','Projetos de IA','Automações','Projetos extensionistas','Projetos integradores','TCCs em desenvolvimento','Interfaces e protótipos','GitHub e portfólio pessoal')),
  resumo text not null check (char_length(trim(resumo)) between 30 and 1500),
  formatos text[] not null check (cardinality(formatos) between 1 and 5),
  necessidades text check (necessidades is null or char_length(necessidades) <= 1000),
  link text check (link is null or char_length(link) <= 500),
  status text not null default 'recebida' check (status in ('recebida','confirmada','cancelada')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.inovatec_participantes (
  id bigint generated by default as identity primary key,
  inscricao_id bigint not null references public.inovatec_inscricoes(id) on delete cascade,
  ordem smallint not null,
  nome text not null check (char_length(trim(nome)) between 3 and 160),
  email text not null check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  whatsapp text not null check (char_length(regexp_replace(whatsapp,'\D','','g')) between 10 and 13),
  criado_em timestamptz not null default now(),
  unique (inscricao_id, ordem)
);

create index if not exists inovatec_inscricoes_criado_idx on public.inovatec_inscricoes (criado_em desc);
create index if not exists inovatec_participantes_inscricao_idx on public.inovatec_participantes (inscricao_id);

alter table public.inovatec_configuracoes enable row level security;
alter table public.inovatec_inscricoes enable row level security;
alter table public.inovatec_participantes enable row level security;

drop policy if exists "Configuracao INOVATEC publica" on public.inovatec_configuracoes;
create policy "Configuracao INOVATEC publica" on public.inovatec_configuracoes for select to anon, authenticated using (true);
drop policy if exists "Coordenacao atualiza INOVATEC" on public.inovatec_configuracoes;
create policy "Coordenacao atualiza INOVATEC" on public.inovatec_configuracoes for update to authenticated using (public.usuario_e_coordenador()) with check (public.usuario_e_coordenador());
drop policy if exists "Coordenacao gerencia inscricoes INOVATEC" on public.inovatec_inscricoes;
create policy "Coordenacao gerencia inscricoes INOVATEC" on public.inovatec_inscricoes for all to authenticated using (public.usuario_e_coordenador()) with check (public.usuario_e_coordenador());
drop policy if exists "Coordenacao gerencia participantes INOVATEC" on public.inovatec_participantes;
create policy "Coordenacao gerencia participantes INOVATEC" on public.inovatec_participantes for all to authenticated using (public.usuario_e_coordenador()) with check (public.usuario_e_coordenador());

revoke all on public.inovatec_inscricoes, public.inovatec_participantes from anon;
grant select on public.inovatec_configuracoes to anon, authenticated;
grant select, update on public.inovatec_configuracoes to authenticated;
grant select, insert, update, delete on public.inovatec_inscricoes, public.inovatec_participantes to authenticated;
grant usage, select on sequence public.inovatec_inscricoes_id_seq, public.inovatec_participantes_id_seq to authenticated;

create or replace function public.enviar_inscricao_inovatec(
  p_titulo text,
  p_curso text,
  p_categoria text,
  p_resumo text,
  p_formatos text[],
  p_necessidades text,
  p_link text,
  p_participantes jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config public.inovatec_configuracoes%rowtype;
  v_id bigint;
  v_item jsonb;
  v_ordem integer := 0;
  v_total integer;
  v_formatos_validos text[] := array['Banner','Notebook próprio','TV ou tela','Demonstração prática','Outro formato'];
begin
  select * into v_config from public.inovatec_configuracoes where id = 1;
  if not found or not v_config.inscricoes_abertas then raise exception 'As inscrições para o INOVATEC estão encerradas.'; end if;
  if p_titulo is null or char_length(trim(p_titulo)) not between 3 and 180 then raise exception 'Título inválido.'; end if;
  if p_curso not in ('ADS','EDC','OUTRO') then raise exception 'Curso inválido.'; end if;
  if p_categoria not in ('Sistemas web','Aplicativos','Jogos','Projetos de redes','Projetos de IA','Automações','Projetos extensionistas','Projetos integradores','TCCs em desenvolvimento','Interfaces e protótipos','GitHub e portfólio pessoal') then raise exception 'Categoria inválida.'; end if;
  if p_resumo is null or char_length(trim(p_resumo)) not between 30 and 1500 then raise exception 'Resumo inválido.'; end if;
  if p_formatos is null or cardinality(p_formatos) < 1 or exists (select 1 from unnest(p_formatos) f where not (f = any(v_formatos_validos))) then raise exception 'Forma de apresentação inválida.'; end if;
  if p_participantes is null or jsonb_typeof(p_participantes) <> 'array' then raise exception 'Participantes inválidos.'; end if;
  v_total := jsonb_array_length(p_participantes);
  if v_total < 1 or v_total > least(v_config.max_participantes,4) then raise exception 'A atividade aceita de 1 a % participantes.', least(v_config.max_participantes,4); end if;
  if p_link is not null and p_link !~* '^https?://' then raise exception 'O link precisa começar com http:// ou https://.'; end if;

  insert into public.inovatec_inscricoes (titulo,curso,categoria,resumo,formatos,necessidades,link)
  values (trim(p_titulo),p_curso,p_categoria,trim(p_resumo),p_formatos,nullif(trim(p_necessidades),''),nullif(trim(p_link),'')) returning id into v_id;

  for v_item in select value from jsonb_array_elements(p_participantes) loop
    v_ordem := v_ordem + 1;
    if char_length(trim(coalesce(v_item->>'nome',''))) < 3 then raise exception 'Nome de participante inválido.'; end if;
    if coalesce(v_item->>'email','') !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'E-mail de participante inválido.'; end if;
    if char_length(regexp_replace(coalesce(v_item->>'whatsapp',''),'\D','','g')) not between 10 and 13 then raise exception 'WhatsApp de participante inválido.'; end if;
    insert into public.inovatec_participantes (inscricao_id,ordem,nome,email,whatsapp)
    values (v_id,v_ordem,trim(v_item->>'nome'),lower(trim(v_item->>'email')),trim(v_item->>'whatsapp'));
  end loop;
  return v_id;
exception when others then
  raise;
end;
$$;

revoke all on function public.enviar_inscricao_inovatec(text,text,text,text,text[],text,text,jsonb) from public;
grant execute on function public.enviar_inscricao_inovatec(text,text,text,text,text[],text,text,jsonb) to anon, authenticated;
