-- Modulo generico de formularios da coordenacao.
-- Primeira categoria: levantamento e acompanhamento de dependencias.

create table if not exists public.formularios (
  id bigint generated by default as identity primary key,
  titulo text not null,
  categoria text not null default 'dependencias',
  descricao text,
  cursos text[] not null default array['ADS','EDC']::text[],
  ativo boolean not null default false,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint formularios_titulo_tamanho check (char_length(titulo) between 3 and 120),
  constraint formularios_descricao_tamanho check (descricao is null or char_length(descricao) <= 1200),
  constraint formularios_cursos_validos check (cursos <@ array['ADS','EDC']::text[] and cardinality(cursos) > 0)
);

create table if not exists public.formulario_respostas (
  id bigint generated by default as identity primary key,
  formulario_id bigint not null references public.formularios(id) on delete cascade,
  nome_estudante text not null,
  curso text not null,
  semestre_atual smallint not null,
  criado_em timestamptz not null default now(),
  constraint formulario_respostas_nome_tamanho check (char_length(nome_estudante) between 3 and 160),
  constraint formulario_respostas_curso_valido check (curso in ('ADS','EDC')),
  constraint formulario_respostas_semestre_valido check (semestre_atual between 1 and 10)
);

create table if not exists public.formulario_resposta_disciplinas (
  resposta_id bigint not null references public.formulario_respostas(id) on delete cascade,
  matriz_disciplina_id bigint not null references public.matriz_disciplinas(id) on delete restrict,
  primary key (resposta_id, matriz_disciplina_id)
);

create index if not exists formulario_respostas_formulario_idx
  on public.formulario_respostas(formulario_id, criado_em desc);

alter table public.formularios enable row level security;
alter table public.formulario_respostas enable row level security;
alter table public.formulario_resposta_disciplinas enable row level security;

drop policy if exists "Formularios ativos sao publicos" on public.formularios;
create policy "Formularios ativos sao publicos"
on public.formularios for select
to anon, authenticated
using (ativo = true or usuario_e_coordenador());

drop policy if exists "Coordenacao gerencia formularios" on public.formularios;
create policy "Coordenacao gerencia formularios"
on public.formularios for all
to authenticated
using (usuario_e_coordenador())
with check (usuario_e_coordenador());

drop policy if exists "Coordenacao gerencia respostas de formularios" on public.formulario_respostas;
create policy "Coordenacao gerencia respostas de formularios"
on public.formulario_respostas for all
to authenticated
using (usuario_e_coordenador())
with check (usuario_e_coordenador());

drop policy if exists "Coordenacao gerencia disciplinas das respostas" on public.formulario_resposta_disciplinas;
create policy "Coordenacao gerencia disciplinas das respostas"
on public.formulario_resposta_disciplinas for all
to authenticated
using (usuario_e_coordenador())
with check (usuario_e_coordenador());

-- O publico nao insere diretamente nas tabelas. Esta funcao valida todos os
-- campos e garante que as disciplinas pertencam a matriz e ao curso informado.
create or replace function public.enviar_formulario_dependencias(
  p_formulario_id bigint,
  p_nome_estudante text,
  p_curso text,
  p_semestre_atual integer,
  p_disciplinas bigint[]
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_formulario public.formularios%rowtype;
  v_resposta_id bigint;
  v_total_validas integer;
begin
  select * into v_formulario
  from public.formularios
  where id = p_formulario_id and ativo = true;

  if not found or v_formulario.categoria <> 'dependencias' then
    raise exception 'Formulario indisponivel';
  end if;
  if p_curso not in ('ADS','EDC') or not (p_curso = any(v_formulario.cursos)) then
    raise exception 'Curso invalido para este formulario';
  end if;
  if char_length(trim(coalesce(p_nome_estudante,''))) not between 3 and 160 then
    raise exception 'Informe o nome completo';
  end if;
  if p_semestre_atual < 1
     or p_semestre_atual > (case when p_curso = 'ADS' then 6 else 10 end) then
    raise exception 'Semestre atual invalido';
  end if;
  if coalesce(cardinality(p_disciplinas),0) < 1 or cardinality(p_disciplinas) > 30 then
    raise exception 'Selecione de 1 a 30 disciplinas';
  end if;

  select count(distinct id) into v_total_validas
  from public.matriz_disciplinas
  where id = any(p_disciplinas) and curso = p_curso and ativa = true;

  if v_total_validas <> cardinality(p_disciplinas) then
    raise exception 'Uma ou mais disciplinas nao pertencem a matriz do curso';
  end if;

  insert into public.formulario_respostas(formulario_id,nome_estudante,curso,semestre_atual)
  values (p_formulario_id,trim(p_nome_estudante),p_curso,p_semestre_atual)
  returning id into v_resposta_id;

  insert into public.formulario_resposta_disciplinas(resposta_id,matriz_disciplina_id)
  select v_resposta_id, id
  from public.matriz_disciplinas
  where id = any(p_disciplinas) and curso = p_curso and ativa = true;

  return v_resposta_id;
end;
$$;

revoke all on function public.enviar_formulario_dependencias(bigint,text,text,integer,bigint[]) from public;
grant execute on function public.enviar_formulario_dependencias(bigint,text,text,integer,bigint[]) to anon, authenticated;

grant select on public.formularios to anon, authenticated;
grant select, insert, update, delete on public.formularios to authenticated;
grant select, insert, update, delete on public.formulario_respostas to authenticated;
grant select, insert, update, delete on public.formulario_resposta_disciplinas to authenticated;
grant usage, select on sequence public.formularios_id_seq to authenticated;

notify pgrst, 'reload schema';
