-- Módulo de submissão de trabalhos do ECEAEMS (Encontro Científico de
-- Estudantes da AEMS). Formulário público em tadsedc.site/eceaems.
--
-- Segue o mesmo padrão já usado em outros formulários públicos do projeto
-- (ex.: supabase_formularios_dependencias.sql): o público NUNCA insere
-- direto nas tabelas — só existe uma função "security definer"
-- (enviar_trabalho_eceaems) que valida tudo no banco antes de gravar.

-- ==========================================================================
-- 1. Configuração (linha única controlada pela coordenação)
-- ==========================================================================

create table if not exists public.eceaems_configuracoes (
  id smallint primary key default 1,
  inscricoes_abertas boolean not null default false,
  max_autores_por_trabalho smallint not null default 3,
  prazo_final date,
  atualizado_em timestamptz not null default now(),
  constraint eceaems_configuracoes_singleton check (id = 1),
  constraint eceaems_configuracoes_max_autores_valido
    check (max_autores_por_trabalho between 1 and 10)
);

insert into public.eceaems_configuracoes (id)
values (1)
on conflict (id) do nothing;

-- ==========================================================================
-- 2. Trabalhos submetidos e autores
-- ==========================================================================

create table if not exists public.eceaems_trabalhos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  curso text not null,
  orientador_id uuid references public.perfis(id) on delete set null,
  orientador_nome text not null,
  disciplina_id bigint references public.matriz_disciplinas(id) on delete set null,
  disciplina_nome text not null,
  arquivo_caminho text not null,
  arquivo_nome_original text not null,
  status text not null default 'recebido',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  constraint eceaems_trabalhos_titulo_tamanho
    check (char_length(trim(titulo)) between 3 and 200),
  constraint eceaems_trabalhos_curso_valido check (curso in ('ADS', 'EDC')),
  constraint eceaems_trabalhos_status_valido
    check (status in ('recebido', 'em_analise', 'aprovado', 'reprovado')),
  constraint eceaems_trabalhos_arquivo_pdf
    check (lower(arquivo_caminho) like '%.pdf')
);

create index if not exists eceaems_trabalhos_criado_idx
  on public.eceaems_trabalhos (criado_em desc);

create table if not exists public.eceaems_autores (
  id bigint generated by default as identity primary key,
  trabalho_id bigint not null references public.eceaems_trabalhos(id) on delete cascade,
  nome text not null,
  email text not null,
  ra text not null,
  criado_em timestamptz not null default now(),
  constraint eceaems_autores_nome_tamanho
    check (char_length(trim(nome)) between 3 and 160),
  constraint eceaems_autores_email_valido
    check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  constraint eceaems_autores_ra_tamanho
    check (char_length(trim(ra)) between 3 and 30)
);

create index if not exists eceaems_autores_trabalho_idx
  on public.eceaems_autores (trabalho_id);

alter table public.eceaems_configuracoes enable row level security;
alter table public.eceaems_trabalhos enable row level security;
alter table public.eceaems_autores enable row level security;

-- A configuração é pública para leitura (o formulário precisa saber se as
-- inscrições estão abertas e quantos autores são permitidos por trabalho).
drop policy if exists "Configuracoes eceaems sao publicas para leitura"
  on public.eceaems_configuracoes;
create policy "Configuracoes eceaems sao publicas para leitura"
on public.eceaems_configuracoes for select
to anon, authenticated
using (true);

drop policy if exists "Coordenacao atualiza configuracoes eceaems"
  on public.eceaems_configuracoes;
create policy "Coordenacao atualiza configuracoes eceaems"
on public.eceaems_configuracoes for update
to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

-- Trabalhos e autores: só a coordenação lê/edita/apaga. O público nunca tem
-- select/insert/update/delete diretos aqui — tudo passa pela função abaixo.
drop policy if exists "Coordenacao gerencia trabalhos eceaems"
  on public.eceaems_trabalhos;
create policy "Coordenacao gerencia trabalhos eceaems"
on public.eceaems_trabalhos for all
to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

drop policy if exists "Coordenacao gerencia autores eceaems"
  on public.eceaems_autores;
create policy "Coordenacao gerencia autores eceaems"
on public.eceaems_autores for all
to authenticated
using (public.usuario_e_coordenador())
with check (public.usuario_e_coordenador());

revoke all on public.eceaems_trabalhos from anon;
revoke all on public.eceaems_autores from anon;
grant select on public.eceaems_configuracoes to anon, authenticated;
grant select, update on public.eceaems_configuracoes to authenticated;
grant select, insert, update, delete on public.eceaems_trabalhos to authenticated;
grant select, insert, update, delete on public.eceaems_autores to authenticated;
grant usage, select on sequence public.eceaems_trabalhos_id_seq to authenticated;
grant usage, select on sequence public.eceaems_autores_id_seq to authenticated;

-- ==========================================================================
-- 3. Armazenamento do PDF (bucket privado, até 10 MB, só PDF)
-- ==========================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'eceaems-artigos',
  'eceaems-artigos',
  false,
  10485760,
  array['application/pdf']
)
on conflict (id) do update
set public = false,
    file_size_limit = 10485760,
    allowed_mime_types = array['application/pdf'];

-- O estudante só pode enviar um PDF para um caminho que comece com um UUID
-- (gerado no navegador antes do envio) — mesmo padrão já usado no bucket de
-- documentos de estágio.
drop policy if exists "Estudante envia artigos do eceaems" on storage.objects;
create policy "Estudante envia artigos do eceaems"
on storage.objects for insert to anon
with check (
  bucket_id = 'eceaems-artigos'
  and lower(right(name, 4)) = '.pdf'
  and split_part(name, '/', 1) ~ '^[0-9a-fA-F-]{36}$'
);

drop policy if exists "Coordenacao le artigos do eceaems" on storage.objects;
create policy "Coordenacao le artigos do eceaems"
on storage.objects for select to authenticated
using (bucket_id = 'eceaems-artigos' and public.usuario_e_coordenador());

drop policy if exists "Coordenacao apaga artigos do eceaems" on storage.objects;
create policy "Coordenacao apaga artigos do eceaems"
on storage.objects for delete to authenticated
using (bucket_id = 'eceaems-artigos' and public.usuario_e_coordenador());

-- ==========================================================================
-- 4. Função pública de envio (valida tudo e grava trabalho + autores)
-- ==========================================================================
--
-- Fluxo esperado do lado do navegador:
--   1) Gera um UUID e faz upload do PDF no bucket eceaems-artigos, no
--      caminho "<uuid>/<nome-do-arquivo>.pdf".
--   2) Chama esta função com os dados do formulário + o caminho do arquivo
--      já enviado + a lista de autores (JSON).
--   3) Se der erro, o arquivo enviado no passo 1 fica órfão no bucket (a
--      coordenação pode limpar manualmente de vez em quando) — o
--      formulário já valida tudo antes de subir o arquivo, então isso deve
--      ser raro na prática.

create or replace function public.enviar_trabalho_eceaems(
  p_titulo text,
  p_curso text,
  p_orientador_id uuid,
  p_disciplina_id bigint,
  p_arquivo_caminho text,
  p_arquivo_nome_original text,
  p_autores jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config public.eceaems_configuracoes%rowtype;
  v_orientador record;
  v_disciplina record;
  v_trabalho_id bigint;
  v_total_autores integer;
  v_autor jsonb;
begin
  select * into v_config from public.eceaems_configuracoes where id = 1;
  if not found or not v_config.inscricoes_abertas then
    raise exception 'As inscrições do ECEAEMS não estão abertas no momento';
  end if;

  if p_curso not in ('ADS', 'EDC') then
    raise exception 'Curso inválido';
  end if;

  if char_length(trim(coalesce(p_titulo, ''))) not between 3 and 200 then
    raise exception 'Informe o título do trabalho';
  end if;

  select p.id, p.nome
    into v_orientador
  from public.perfis p
  where p.id = p_orientador_id
    and p.papel = 'professor'
    and p.ativo = true;

  if not found then
    raise exception 'Selecione um professor orientador válido';
  end if;

  select m.id, m.disciplina
    into v_disciplina
  from public.matriz_disciplinas m
  where m.id = p_disciplina_id
    and m.curso = p_curso
    and m.ativa = true;

  if not found then
    raise exception 'Selecione uma disciplina válida da matriz do curso escolhido';
  end if;

  if p_arquivo_caminho is null or lower(p_arquivo_caminho) not like '%.pdf' then
    raise exception 'Envie o artigo em formato PDF';
  end if;

  if jsonb_typeof(p_autores) is distinct from 'array' then
    raise exception 'Lista de autores inválida';
  end if;

  v_total_autores := jsonb_array_length(p_autores);
  if v_total_autores < 1 or v_total_autores > v_config.max_autores_por_trabalho then
    raise exception 'Este trabalho aceita de 1 a % autor(es)', v_config.max_autores_por_trabalho;
  end if;

  for v_autor in select * from jsonb_array_elements(p_autores)
  loop
    if char_length(trim(coalesce(v_autor->>'nome', ''))) not between 3 and 160 then
      raise exception 'Informe o nome completo de todos os autores';
    end if;
    if coalesce(v_autor->>'email', '') !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
      raise exception 'Informe um e-mail válido para todos os autores';
    end if;
    if char_length(trim(coalesce(v_autor->>'ra', ''))) not between 3 and 30 then
      raise exception 'Informe a matrícula (RA) de todos os autores';
    end if;
  end loop;

  insert into public.eceaems_trabalhos
    (titulo, curso, orientador_id, orientador_nome, disciplina_id, disciplina_nome,
     arquivo_caminho, arquivo_nome_original)
  values
    (trim(p_titulo), p_curso, v_orientador.id, v_orientador.nome, v_disciplina.id,
     v_disciplina.disciplina, p_arquivo_caminho, coalesce(p_arquivo_nome_original, 'artigo.pdf'))
  returning id into v_trabalho_id;

  insert into public.eceaems_autores (trabalho_id, nome, email, ra)
  select v_trabalho_id, trim(elem->>'nome'), lower(trim(elem->>'email')), trim(elem->>'ra')
  from jsonb_array_elements(p_autores) as elem;

  return v_trabalho_id;
end;
$$;

revoke all on function public.enviar_trabalho_eceaems(text, text, uuid, bigint, text, text, jsonb) from public;
grant execute on function public.enviar_trabalho_eceaems(text, text, uuid, bigint, text, text, jsonb) to anon, authenticated;

notify pgrst, 'reload schema';
