-- Atividade de professores: leitura restrita à coordenação.
create table if not exists public.historico_alteracoes_sala (
  id bigint generated by default as identity primary key,
  professor_id uuid not null references public.perfis(id) on delete cascade,
  aula_id bigint not null references public.aulas(id) on delete cascade,
  sala_id bigint references public.salas(id) on delete set null,
  alterado_em timestamptz not null default clock_timestamp()
);

alter table public.historico_alteracoes_sala enable row level security;

drop policy if exists "Coordenacao consulta historico de salas"
  on public.historico_alteracoes_sala;
create policy "Coordenacao consulta historico de salas"
  on public.historico_alteracoes_sala
  for select to authenticated
  using (public.e_coordenador());

create or replace function public.registrar_historico_alteracao_sala()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.sala_padrao_id is distinct from old.sala_padrao_id
     and exists (
       select 1 from public.perfis p
       where p.id = auth.uid()
         and p.papel = 'professor'
         and p.ativo = true
     )
     and new.professor_id = auth.uid()
  then
    insert into public.historico_alteracoes_sala
      (professor_id, aula_id, sala_id)
    values
      (auth.uid(), new.id, new.sala_padrao_id);
  end if;
  return new;
end;
$$;

drop trigger if exists registrar_historico_alteracao_sala
  on public.aulas;
create trigger registrar_historico_alteracao_sala
after update of sala_padrao_id on public.aulas
for each row execute function public.registrar_historico_alteracao_sala();

create or replace function public.listar_atividade_professores()
returns table (
  professor_id uuid,
  nome text,
  email text,
  ultimo_login_em timestamptz,
  ultima_alteracao_sala_em timestamptz,
  disciplina text,
  sala text
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.e_coordenador() then
    raise exception 'Acesso exclusivo da coordenação';
  end if;

  return query
  select
    p.id,
    p.nome,
    p.email,
    u.last_sign_in_at,
    h.alterado_em,
    a.disciplina,
    s.nome
  from public.perfis p
  left join auth.users u on u.id = p.id
  left join lateral (
    select x.aula_id, x.sala_id, x.alterado_em
    from public.historico_alteracoes_sala x
    where x.professor_id = p.id
    order by x.alterado_em desc
    limit 1
  ) h on true
  left join public.aulas a on a.id = h.aula_id
  left join public.salas s on s.id = h.sala_id
  where p.papel = 'professor'
    and p.ativo = true
  order by p.nome;
end;
$$;

revoke all on function public.listar_atividade_professores() from public;
grant execute on function public.listar_atividade_professores() to authenticated;
revoke all on table public.historico_alteracoes_sala from anon;
