const SUPABASE_URL='https://uvdnejmdqgwdcipctyur.supabase.co';
const SUPABASE_KEY='sb_publishable_Afn5llFEgcHD4Uhmt8N4pA_W0T_NHZk';
let api=null;try{api=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}catch(e){console.error('Falha ao inicializar o Supabase (CDN pode não ter carregado):',e)}
const DAYS=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const SHORT=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const state={course:'',view:'schedule',day:(()=>{const d=new Date().getDay();return d>0&&d<7?d:1})(),group:'all',dateGroup:'all',datePicker:false,loading:false,error:'',teacherInfo:null};
let lastDataSync=0,refreshInFlight=null;
const db={rooms:[],groups:[],classes:[],notices:[],teachers:[],dates:[],forms:[],curriculum:[],materials:[],dateGroupsLoaded:false};
const SITE_BASE=location.hostname.endsWith('github.io')?'/coordenacao':'';
const sitePath=(path='/')=>`${SITE_BASE}${path}`;
function courseFromPath(){const path=location.pathname.replace(/\/+$/,'').toLowerCase();return path.endsWith('/ads')?'ADS':path.endsWith('/edc')?'EDC':''}
function updatePublicPath(course='',replace=false){const target=course?sitePath(`/${course.toLowerCase()}/`):sitePath('/');if(location.pathname!==target)history[replace?'replaceState':'pushState']({},'',target)}
function showCourseSelector(){updatePublicPath();showWelcome()}
const icon=(name)=>({home:'<path d="M3 11.5 12 4l9 7.5V21H3Z"/><path d="M9 21v-6h6v6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',notice:'<path d="M4 4h16v13H7l-3 3Z"/><path d="M8 9h8M8 13h5"/>',form:'<path d="M6 2h9l5 5v15H6Z"/><path d="M14 2v6h6M9 13h8M9 17h6"/>',people:'<circle cx="9" cy="8" r="4"/><path d="M2 21a7 7 0 0 1 14 0M16 4a4 4 0 0 1 0 8M17 14a7 7 0 0 1 5 7"/>',code:'<path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14"/>',chip:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 1v5M15 1v5M9 18v5M15 18v5M1 9h5M1 15h5M18 9h5M18 15h5"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',arrow:'<path d="m9 18 6-6-6-6"/>',back:'<path d="m15 18-6-6 6-6"/>',external:'<path d="M15 3h6v6M10 14 21 3M18 13v8H3V6h8"/>'}[name]||'');
const svg=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon(name)}</svg>`;
function wordmark(){return `<div class="wordmark"><span class="wordmark-mark">${svg('code')}</span><span class="wordmark-copy"><span class="wordmark-name"><b>Coordenação</b><em>TADS e EDC - AEMS</em></span></span></div>`}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function courseName(c){return c==='ADS'?'Análise e Desenvolvimento de Sistemas':'Engenharia de Computação'}
function formatDate(v){return new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}
function showWelcome(){state.course='';document.title='Coordenação de TADS e EDC - AEMS';document.getElementById('app').innerHTML=`<header class="public-header"><div class="public-header-inner">${wordmark()}<div class="header-links"><a href="${sitePath('/professor/')}">Professor</a><a href="https://apps.aems.edu.br/aluno/login" target="_blank" rel="noopener">Área do Aluno</a><a href="${sitePath('/estagio/')}">Estágio</a></div></div></header><main class="welcome-main"><section class="welcome-intro"><p class="eyebrow">Portal de comunicação acadêmica</p><h1>Escolha o <span>seu curso</span></h1><div class="welcome-chips"><span>Grade semanal</span><span>Salas atualizadas</span><span>Informes acadêmicos</span><span>Datas importantes</span></div></section><div class="course-choices"><button class="course-choice" style="--choice:#3157e2" data-course="ADS"><span class="choice-icon">${svg('code')}</span><span class="choice-copy"><small>Tecnologia e software</small><b>Análise e Desenvolvimento de Sistemas</b><p>Acesse horários, salas e informações acadêmicas de ADS.</p></span><span class="choice-arrow">${svg('arrow')}</span></button><button class="course-choice" style="--choice:#e49c21" data-course="EDC"><span class="choice-icon">${svg('chip')}</span><span class="choice-copy"><small>Engenharia e inovação</small><b>Engenharia de Computação</b><p>Acesse horários, salas e informações acadêmicas de EDC.</p></span><span class="choice-arrow">${svg('arrow')}</span></button><a class="student-choice" href="https://apps.aems.edu.br/aluno/login" target="_blank" rel="noopener"><span class="choice-icon">${svg('external')}</span><span class="choice-copy"><small>Serviços institucionais</small><b>Área do Aluno AEMS</b><p>Boletim, requerimentos e informações financeiras.</p></span><span class="choice-arrow">${svg('arrow')}</span></a></div><div class="welcome-note"><b>Importante</b><p>Este portal facilita a comunicação da coordenação com os estudantes e não substitui a Área do Aluno oficial da AEMS.</p></div></main>`;document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>openCourse(b.dataset.course))}
function navItems(){return [['schedule','home','Horários'],['notices','notice','Informes'],['dates','calendar','Datas'],['forms','form','Formulários']]}
function portalShell(content){const nav=navItems().map(([id,ic,label])=>`<button data-view="${id}" class="${state.view===id?'active':''}">${svg(ic)}<span>${label}</span></button>`).join('');return `<div class="portal"><header class="public-header compact"><div class="public-header-inner">${wordmark()}<div class="portal-access"><button class="access-toggle" data-access-toggle aria-expanded="false"><span class="menu-glyph">☰</span><span>Acessos</span></button><div class="header-links access-popover"><a href="${sitePath('/professor/')}">Professor</a><a href="https://apps.aems.edu.br/aluno/login" target="_blank" rel="noopener">Área do Aluno</a><a href="${sitePath('/estagio/')}">Estágio</a><button data-change-course>Trocar curso</button></div></div></div></header><main class="main"><section class="course-banner ${state.course.toLowerCase()}"><button class="banner-back" data-change-course aria-label="Trocar curso">${svg('back')}</button><div><small>Curso selecionado</small><h1>${escapeHtml(courseName(state.course))}</h1><p>Horários, salas e comunicação da coordenação.</p></div><span class="course-code">${state.course}</span></section><nav class="floating-nav">${nav}</nav><div class="page-content">${content}</div></main><nav class="bottom-dock">${nav}</nav></div>`}
function hero(){return `<section class="section-intro section-intro-${state.view}"><div><p class="eyebrow">${state.course} · Informação acadêmica</p><h1>${state.view==='schedule'?'Horários e salas':state.view==='notices'?'Informes da coordenação':state.view==='dates'?'Datas importantes':'Formulários'}</h1></div></section>`}
const isAttendance=c=>String(c?.code||'').toUpperCase()==='ATENDIMENTO';
function scheduleView(){const availableGroups=db.groups.filter(g=>(g.cursos||[]).includes(state.course));const groupsOptions=availableGroups.map(g=>`<option value="${g.id}" ${String(state.group)===String(g.id)?'selected':''}>${escapeHtml(g.nome)} · ${state.course}</option>`).join('');const items=db.classes.filter(c=>c.courses.includes(state.course)&&Number(c.day)===state.day&&(isAttendance(c)||state.group==='all'||c.groupIds.includes(Number(state.group)))).sort((a,b)=>Number(isAttendance(b))-Number(isAttendance(a))||String(a.start).localeCompare(String(b.start)));return `${hero()}<div class="filters"><div class="day-list">${[1,2,3,4,5,6].map(d=>`<button class="day-btn ${state.day===d?'active':''}" data-day="${d}">${SHORT[d]}</button>`).join('')}</div><label class="select-wrap"><select id="group-filter"><option value="all">Todas as turmas</option>${groupsOptions}</select></label></div><div class="schedule-grid">${items.length?items.map((c,i)=>lessonCard(c,i)).join(''):'<div class="empty">Nenhuma aula encontrada para este filtro.</div>'}</div>`}
function lessonCard(c,i){if(isAttendance(c))return attendanceCard(c,i);const semi=c.code==='SEMIPRESENCIAL'||c.teacher==='Mediador Pedagógico',r=db.rooms.find(x=>Number(x.id)===Number(c.roomId));const roomName=semi?'Online no grupoau.com.br':r?`${r.nome}`:'Sala ainda não informada pelo professor';const detail=semi?'Ambiente virtual de aprendizagem':r?[r.predio,r.andar].filter(Boolean).join(' · '):'Consulte novamente em breve';const teacher=semi?`<span class="teacher">Mediador Pedagógico</span>`:`<button class="teacher teacher-trigger" data-teacher="${escapeHtml(c.professor_id)}" data-subject="${escapeHtml(c.subject)}">${escapeHtml(c.teacher||'Professor')} <span>i</span></button>`;const tags=c.groups.map(g=>{const courses=Array.isArray(g.cursos)?g.cursos.filter(Boolean):[];const tone=courses.length===1?String(courses[0]).toLowerCase():'shared';const label=[g.nome,courses.join(' + ')].filter(Boolean).join(' · ');return `<span class="tag ${escapeHtml(tone)}">${escapeHtml(label)}</span>`}).join('')||c.courses.map(course=>`<span class="tag ${escapeHtml(String(course).toLowerCase())}">${escapeHtml(course)}</span>`).join('');return `<article class="lesson" style="animation-delay:${Math.min(i,8)*45}ms;--course-color:${state.course==='ADS'?'#3157e2':'#e49c21'}"><div class="lesson-top"><div class="lesson-time">${semi?'Online':escapeHtml(c.start)}<small>${semi?'Sem bloco de horário':`até ${escapeHtml(c.end)}`}</small></div><div class="lesson-tags">${tags}</div></div><h3>${escapeHtml(c.subject)}</h3>${teacher}<div class="room"><span class="room-icon">${svg('pin')}</span><div><b>${escapeHtml(roomName)}</b><small>${escapeHtml(detail)}</small></div></div></article>`}
function attendanceCard(c,i){const r=db.rooms.find(x=>Number(x.id)===Number(c.roomId)),roomName=r?r.nome:'Local ainda não informado',detail=r?[r.predio,r.andar].filter(Boolean).join(' · '):'Consulte a coordenação do curso';return `<article class="lesson student-support-card" style="animation-delay:${Math.min(i,8)*45}ms"><span class="support-ribbon">Atendimento da coordenação</span><div class="lesson-top"><div class="lesson-time">${escapeHtml(c.start)}<small>até ${escapeHtml(c.end)}</small></div><span class="support-badge">Aberto aos estudantes</span></div><h3>${escapeHtml(c.subject||'ATENDIMENTO AO ESTUDANTE')}</h3><span class="teacher support-owner">${escapeHtml(c.teacher||'Coordenação do Curso')}</span><div class="room"><span class="room-icon">${svg('pin')}</span><div><b>${escapeHtml(roomName)}</b><small>${escapeHtml(detail)}</small></div></div></article>`}
function noticesView(){const items=db.notices.filter(n=>(n.cursos||[]).includes(state.course));return `${hero()}<div class="section-heading"><div><h2>Informes da coordenação</h2><p>Recados e orientações para o seu curso.</p></div><span class="count">${items.length} informe(s)</span></div><div class="content-grid">${items.length?items.map((n,i)=>`<article class="notice-card ${i===0?'featured':''}" style="animation-delay:${i*50}ms"><span class="notice-date">${new Date(n.publicado_em).toLocaleDateString('pt-BR')}</span><h3>${escapeHtml(n.titulo)}</h3><p>${escapeHtml(n.conteudo)}</p></article>`).join(''):'<div class="empty">Nenhum informe publicado neste momento.</div>'}</div>`}
function teachersView(){const teacherIds=new Set(db.classes.filter(c=>c.courses.includes(state.course)).map(c=>String(c.professor_id)).filter(Boolean));const items=db.teachers.filter(t=>teacherIds.has(String(t.id)));return `${hero()}<div class="section-heading"><div><h2>Professores</h2><p>Contatos da equipe que atua no curso.</p></div><span class="count">${items.length} docente(s)</span></div><div class="content-grid">${items.length?items.map((t,i)=>{const initials=(t.nome||'P').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return `<article class="teacher-card" style="animation-delay:${i*45}ms"><div class="avatar">${t.avatar_url?`<img class="avatar" src="${escapeHtml(t.avatar_url)}" alt="">`:initials}</div><h3>${escapeHtml(t.nome)}</h3><a href="mailto:${escapeHtml(t.email)}">${escapeHtml(t.email)}</a><div class="teacher-chip">${(t.contatos||[]).map(x=>x==='Somente presencial'?'E-mail':x).join(' · ')||'Contato por e-mail'}</div></article>`}).join(''):'<div class="empty">Nenhum professor vinculado às aulas deste curso.</div>'}</div>`}
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function materialLabel(type){return type==='Google Classroom'?'Classroom':type==='Outro'?'Link':type||'Material'}
function teacherPanel(){if(!state.teacherInfo)return'';const teacher=db.teachers.find(t=>String(t.id)===String(state.teacherInfo.id));if(!teacher)return'';const related=db.materials.filter(m=>String(m.professor_id)===String(teacher.id)&&normalize(m.disciplina)===normalize(state.teacherInfo.subject)),other=db.materials.filter(m=>String(m.professor_id)===String(teacher.id)&&normalize(m.disciplina)!==normalize(state.teacherInfo.subject));const rows=items=>items.length?`<div class="teacher-materials">${items.map(m=>`<a href="${escapeHtml(m.url)}" target="_blank" rel="noopener"><span>${escapeHtml(materialLabel(m.tipo))}</span><b>${escapeHtml(m.disciplina)} ↗</b></a>`).join('')}</div>`:'<p class="muted">Nenhum material cadastrado para esta disciplina.</p>';const initials=(teacher.nome||'P').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const general=(teacher.materiais||[]).filter(x=>['Área do Aluno AEMS','Portal do Aluno','GrupoAU'].includes(x));return `<div class="teacher-sheet-bg" data-close-teacher><section class="teacher-sheet" role="dialog" aria-modal="true" onclick="event.stopPropagation()"><div class="sheet-handle"></div><button class="sheet-close" data-close-teacher>×</button><header><div class="sheet-avatar">${teacher.avatar_url?`<img src="${escapeHtml(teacher.avatar_url)}" alt="">`:initials}</div><div><small>Professor da disciplina</small><h2>${escapeHtml(teacher.nome)}</h2><span>${escapeHtml(state.teacherInfo.subject)}</span></div></header><div class="sheet-grid"><div class="sheet-section"><small>E-mail institucional</small><a href="mailto:${escapeHtml(teacher.email)}">${escapeHtml(teacher.email)}</a></div><div class="sheet-section"><small>Como entrar em contato</small><p>${escapeHtml((teacher.contatos||[]).map(x=>x==='Somente presencial'?'E-mail':x).join(' · ')||'E-mail')}</p>${teacher.whatsapp?`<p>${escapeHtml(teacher.whatsapp)}</p>`:''}</div></div><div class="sheet-section related"><small>Materiais desta disciplina</small>${rows(related)}</div>${general.length?`<div class="sheet-section"><small>Materiais gerais</small><p>${general.map(escapeHtml).join(' · ')}</p></div>`:''}${other.length?`<details><summary>Ver outros materiais do professor</summary>${rows(other)}</details>`:''}</section></div>`}
function formsView(){const forms=db.forms.filter(f=>f.ativo&&(f.cursos||[]).includes(state.course));return `${hero()}<div class="section-heading"><div><h2>Formulários disponíveis</h2><p>Levantamentos acadêmicos publicados pela coordenação.</p></div><span class="count">${forms.length} formulário(s)</span></div><div class="forms-public">${forms.length?forms.map(publicForm).join(''):'<div class="empty">Nenhum formulário está disponível no momento.</div>'}</div>`}
function publicForm(f){const max=state.course==='ADS'?6:10,disc=db.curriculum.filter(d=>d.curso===state.course).sort((a,b)=>a.semestre-b.semestre||a.disciplina.localeCompare(b.disciplina)),semesters=[...new Set(disc.map(d=>d.semestre))];return `<article class="public-form"><span class="form-badge">DEPENDÊNCIAS</span><h2>${escapeHtml(f.titulo)}</h2><p>${escapeHtml(f.descricao||'Informe as disciplinas em que você possui dependência para acompanhamento da coordenação.')}</p><form data-form="${f.id}"><div class="form-row"><label><b>Nome completo</b><input name="student-name" maxlength="160" required autocomplete="name"></label><label><b>Semestre atual</b><select name="semester" required><option value="">Selecione</option>${Array.from({length:max},(_,i)=>`<option value="${i+1}">${i+1}º semestre</option>`).join('')}</select></label></div><div class="dependency-head"><b>Disciplinas em dependência</b><p>Selecione uma ou mais disciplinas da matriz de ${state.course}.</p></div><div class="matrix-groups">${semesters.map(s=>`<section><h3>${s}º semestre da matriz</h3><div>${disc.filter(d=>d.semestre===s).map(d=>`<label><input type="checkbox" value="${d.id}"><span>${escapeHtml(d.disciplina)}</span></label>`).join('')}</div></section>`).join('')}</div><div class="privacy-hint">As informações serão acessadas somente pela coordenação e não ficarão públicas.</div><button class="submit-form" type="submit">Enviar para a coordenação</button></form></article>`}
function toast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),4200)}
async function submitPublicForm(form){const name=form.elements['student-name'].value.trim().toLocaleUpperCase('pt-BR'),semester=+form.elements.semester.value,ids=[...form.querySelectorAll('input[type="checkbox"]:checked')].map(x=>+x.value);if(!name||!semester||!ids.length)return toast('Preencha o nome, o semestre e selecione ao menos uma disciplina.');const button=form.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Enviando…';const {error}=await api.rpc('enviar_formulario_dependencias',{p_formulario_id:+form.dataset.form,p_nome_estudante:name,p_curso:state.course,p_semestre_atual:semester,p_disciplinas:ids});button.disabled=false;button.textContent='Enviar para a coordenação';if(error)return toast('Não foi possível enviar: '+error.message);form.reset();toast('Informações enviadas para a coordenação.')}
async function loadDateGroups(){const {data,error}=await api.from('avaliacao_turmas').select('avaliacao_id,turma_id,turmas(id,nome,cursos)');if(error){console.warn('Vínculos das datas por turma indisponíveis:',error.message);db.dates.forEach(d=>{d.groups=[];d.groupIds=[]});db.dateGroupsLoaded=true;return}const byDate={};(data||[]).forEach(link=>{const group=link.turmas||db.groups.find(g=>Number(g.id)===Number(link.turma_id));if(group)(byDate[link.avaliacao_id]??=[]).push(group)});db.dates.forEach(d=>{d.groups=byDate[d.id]||[];d.groupIds=d.groups.map(g=>Number(g.id))});db.dateGroupsLoaded=true}
function dateGroupFilter(groups){const selected=state.dateGroup==='all'?null:groups.find(g=>String(g.id)===String(state.dateGroup)),label=selected?`${selected.nome} · ${state.course}`:'Todas as turmas';return `<div class="date-group-filter"><button class="date-group-trigger ${state.datePicker?'open':''}" data-date-picker aria-expanded="${state.datePicker}"><span class="date-filter-icon">${svg('calendar')}</span><span><small>Visualizar datas da turma</small><b>${escapeHtml(label)}</b></span><span class="date-filter-arrow">⌄</span></button>${state.datePicker?`<div class="date-group-options"><button data-date-group="all" class="${state.dateGroup==='all'?'active':''}"><span class="date-option-icon">∞</span><span><b>Todas as turmas</b><small>Agenda completa de ${state.course}</small></span></button>${groups.map(g=>`<button data-date-group="${g.id}" class="${String(state.dateGroup)===String(g.id)?'active':''}"><span class="date-option-icon">${escapeHtml(String(g.nome).slice(0,2))}</span><span><b>${escapeHtml(g.nome)}</b><small>${escapeHtml(state.course)}</small></span></button>`).join('')}</div>`:''}</div>`}
function datesView(){const groups=db.groups.filter(g=>(g.cursos||[]).includes(state.course));if(state.dateGroup!=='all'&&!groups.some(g=>String(g.id)===String(state.dateGroup))){state.dateGroup='all';state.datePicker=false}const base=db.dates.filter(d=>(d.cursos||[]).includes(state.course)),items=base.filter(d=>state.dateGroup==='all'||!(d.groupIds||[]).length||(d.groupIds||[]).map(String).includes(String(state.dateGroup)));const color=t=>t.includes('Exame')?'#e5b12e':t.includes('Substitutiva')?'#23745d':t.includes('P1')||t.includes('P2')?'#4fae76':'#546ee8';return `${hero()}<div class="section-heading"><div><h2>Datas importantes</h2><p>Avaliações, eventos e marcos acadêmicos.</p></div><span class="count">${items.length} data(s)</span></div>${dateGroupFilter(groups)}<div class="content-grid">${items.length?items.map((d,i)=>`<article class="date-card" style="--date:${color(d.tipo||'')};animation-delay:${i*45}ms"><span class="card-label">${escapeHtml(d.tipo)}</span><h3>${escapeHtml(d.disciplina||d.titulo||'Data importante')}</h3><div class="date-day">${formatDate(d.data)}</div><p>${escapeHtml(d.professor_nome||'Coordenação do curso')}</p>${d.salas?`<p>${escapeHtml(d.salas.nome)} · ${escapeHtml(d.salas.predio||'')}</p>`:''}${(d.groups||[]).length?`<div class="date-card-groups">${d.groups.map(g=>`<span class="${(g.cursos||[])[0]==='EDC'?'edc':''}">${escapeHtml(g.nome)} · ${escapeHtml((g.cursos||[]).join(' + '))}</span>`).join('')}</div>`:'<div class="date-card-groups"><span>Todos do curso</span></div>'}</article>`).join(''):'<div class="empty">Nenhuma data importante cadastrada para esta turma.</div>'}</div>`}
function renderPortal(){let content=state.view==='schedule'?scheduleView():state.view==='notices'?noticesView():state.view==='dates'?datesView():formsView();document.getElementById('app').innerHTML=portalShell(content)+teacherPanel();bindPortal()}
function bindPortal(){document.querySelectorAll('[data-change-course]').forEach(b=>b.onclick=showWelcome);document.querySelector('[data-access-toggle]')?.addEventListener('click',e=>{const access=e.currentTarget.closest('.portal-access');const open=access.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});document.addEventListener('click',e=>{const access=document.querySelector('.portal-access');if(access&&!access.contains(e.target)){access.classList.remove('open');access.querySelector('[data-access-toggle]')?.setAttribute('aria-expanded','false')}},{once:true});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.teacherInfo=null;state.datePicker=false;renderPortal();scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.day);renderPortal()});document.getElementById('group-filter')?.addEventListener('change',e=>{state.group=e.target.value;renderPortal()});document.querySelector('[data-date-picker]')?.addEventListener('click',()=>{state.datePicker=!state.datePicker;renderPortal()});document.querySelectorAll('[data-date-group]').forEach(b=>b.onclick=()=>{state.dateGroup=b.dataset.dateGroup;state.datePicker=false;renderPortal()});document.querySelectorAll('[data-teacher]').forEach(b=>b.onclick=()=>{state.teacherInfo={id:b.dataset.teacher,subject:b.dataset.subject};renderPortal()});document.querySelectorAll('[data-close-teacher]').forEach(b=>b.onclick=()=>{state.teacherInfo=null;renderPortal()});document.querySelectorAll('[data-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();submitPublicForm(f)})}
const bindPortalBase=bindPortal;
bindPortal=function(){bindPortalBase();document.querySelectorAll('[data-change-course]').forEach(b=>b.onclick=showCourseSelector)};
function loading(){document.getElementById('app').innerHTML=`<div class="loading"><div><div class="loader-orbit"></div><p>Organizando suas informações…</p></div></div>`}
async function loadData(){const [rooms,groups,classes,links,notices,teachers,dates,forms,curriculum,materials,currentTeachers]=await Promise.all([api.from('salas').select('id,nome,predio,andar').eq('ativa',true).order('nome'),api.from('turmas').select('id,nome,cursos').eq('ativa',true).order('id'),api.from('aulas').select('id,codigo,disciplina,professor_id,professor_nome,turma_id,cursos,dia_semana,inicio,fim,sala_padrao_id,sala_base_id').eq('ativa',true).order('inicio'),api.from('aula_turmas').select('aula_id,turma_id,turmas(id,nome,cursos)'),api.from('informes').select('id,titulo,conteudo,cursos,publicado_em').eq('ativo',true).order('publicado_em',{ascending:false}),api.from('professores_publicos').select('*').order('nome'),api.from('avaliacoes').select('*,salas(nome,predio)').eq('ativo',true).order('data'),api.from('formularios').select('*').eq('ativo',true).order('criado_em',{ascending:false}),api.from('matriz_disciplinas').select('id,curso,semestre,disciplina').eq('ativa',true).order('curso').order('semestre').order('disciplina'),api.from('professor_materiais').select('professor_id,disciplina,tipo,url').eq('ativo',true).order('disciplina'),api.from('aulas_professores_atuais').select('aula_id,professor_id,professor_nome')]);const core=[rooms,groups,classes,links,notices,teachers,dates].find(x=>x.error);if(core)throw core.error;db.rooms=rooms.data||[];db.groups=groups.data||[];const byClass={};(links.data||[]).forEach(l=>{const group=l.turmas||db.groups.find(g=>Number(g.id)===Number(l.turma_id));if(group)(byClass[l.aula_id]??=[]).push(group)});const effectiveByClass=new Map((currentTeachers.error?[]:currentTeachers.data||[]).map(item=>[String(item.aula_id),item]));db.classes=(classes.data||[]).map(c=>{let assigned=byClass[c.id]||[];if(!assigned.length&&c.turma_id&&String(c.codigo).toUpperCase()!=='ATENDIMENTO'){const fallback=db.groups.find(g=>Number(g.id)===Number(c.turma_id));if(fallback)assigned=[fallback]}const assignedCourses=[...new Set(assigned.flatMap(g=>Array.isArray(g.cursos)?g.cursos:[]).filter(Boolean))];const effective=effectiveByClass.get(String(c.id));return{id:c.id,code:c.codigo,subject:c.disciplina,teacher:effective?.professor_nome||c.professor_nome,professor_id:effective?.professor_id||c.professor_id,holderTeacher:c.professor_nome,holderProfessorId:c.professor_id,coverageActive:Boolean(effective&&String(effective.professor_id)!==String(c.professor_id)),courses:assignedCourses.length?assignedCourses:c.cursos||[],day:c.dia_semana,start:String(c.inicio).slice(0,5),end:String(c.fim).slice(0,5),roomId:c.sala_padrao_id||c.sala_base_id,groups:assigned,groupIds:assigned.map(g=>Number(g.id))}});db.notices=notices.data||[];db.teachers=teachers.data||[];db.dates=dates.data||[];db.forms=forms.error?[]:forms.data||[];db.curriculum=curriculum.error?[]:curriculum.data||[];db.materials=materials.error?[]:materials.data||[];lastDataSync=Date.now()}
async function openCourse(course,{updatePath=true}={}){course=String(course).toUpperCase();if(!['ADS','EDC'].includes(course))return showCourseSelector();if(updatePath)updatePublicPath(course);document.title=`${courseName(course)} - Coordenação TADS e EDC`;state.course=course;state.view='schedule';state.group='all';state.dateGroup='all';state.datePicker=false;loading();try{await loadData();await loadDateGroups();renderPortal()}catch(error){console.error(error);document.getElementById('app').innerHTML=`<div class="error-card"><h2>Não foi possível carregar o portal</h2><p>Verifique sua conexão e tente novamente.</p><button id="retry">Tentar novamente</button></div>`;document.getElementById('retry').onclick=()=>openCourse(course,{updatePath:false})}}
async function refreshPortalIfStale(){if(!state.course||document.hidden||Date.now()-lastDataSync<30000||refreshInFlight)return;refreshInFlight=loadData();try{await refreshInFlight;document.documentElement.classList.add('silent-data-refresh');renderPortal();requestAnimationFrame(()=>requestAnimationFrame(()=>document.documentElement.classList.remove('silent-data-refresh')))}catch(error){console.warn('Atualização silenciosa:',error.message)}finally{refreshInFlight=null}}
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.teacherInfo){state.teacherInfo=null;renderPortal()}});
document.addEventListener('click',event=>{const access=document.querySelector('.portal-access');if(access&&!event.target.closest('.portal-access')){access.classList.remove('open');access.querySelector('[data-access-toggle]')?.setAttribute('aria-expanded','false')}});
document.addEventListener('visibilitychange',refreshPortalIfStale);
window.addEventListener('focus',refreshPortalIfStale);
window.addEventListener('popstate',()=>{const course=courseFromPath();course?openCourse(course,{updatePath:false}):showWelcome()});
const initialCourse=courseFromPath();
initialCourse?openCourse(initialCourse,{updatePath:false}):showWelcome();

/* As rotas de acesso usam diretamente as telas renovadas, sem páginas intermediárias. */
(function(){
  const freshRoutes={
    '/professor-novo/':sitePath('/professor/'),
    '/estagio-novo/':sitePath('/estagio/')
  };
  function refreshAccessRoutes(scope=document){
    scope.querySelectorAll('a[href]').forEach(link=>{
      const href=link.getAttribute('href');
      if(freshRoutes[href])link.setAttribute('href',freshRoutes[href]);
    });
  }
  const renderWelcomeBeforeRoutes=showWelcome;
  showWelcome=function(){renderWelcomeBeforeRoutes();refreshAccessRoutes()};
  const renderPortalBeforeRoutes=renderPortal;
  renderPortal=function(){renderPortalBeforeRoutes();refreshAccessRoutes()};
  refreshAccessRoutes();
})();
