const SUPABASE_URL='https://uvdnejmdqgwdcipctyur.supabase.co';
const SUPABASE_KEY='sb_publishable_Afn5llFEgcHD4Uhmt8N4pA_W0T_NHZk';
const api=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const DAYS=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const SHORT=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const state={course:'',view:'schedule',day:(()=>{const d=new Date().getDay();return d>0&&d<7?d:1})(),group:'all',loading:false,error:''};
const db={rooms:[],groups:[],classes:[],notices:[],teachers:[],dates:[]};
const icon=(name)=>({home:'<path d="M3 11.5 12 4l9 7.5V21H3Z"/><path d="M9 21v-6h6v6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',notice:'<path d="M4 4h16v13H7l-3 3Z"/><path d="M8 9h8M8 13h5"/>',people:'<circle cx="9" cy="8" r="4"/><path d="M2 21a7 7 0 0 1 14 0M16 4a4 4 0 0 1 0 8M17 14a7 7 0 0 1 5 7"/>',code:'<path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14"/>',chip:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 1v5M15 1v5M9 18v5M15 18v5M1 9h5M1 15h5M18 9h5M18 15h5"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',arrow:'<path d="m9 18 6-6-6-6"/>',back:'<path d="m15 18-6-6 6-6"/>',external:'<path d="M15 3h6v6M10 14 21 3M18 13v8H3V6h8"/>'}[name]||'');
const svg=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon(name)}</svg>`;
function wordmark(){return `<div class="wordmark"><span class="wordmark-mark">${svg('code')}</span><span>Portal da Coordenação<small>TADS e EDC · AEMS</small></span></div>`}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function courseName(c){return c==='ADS'?'Análise e Desenvolvimento de Sistemas':'Engenharia de Computação'}
function formatDate(v){return new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}
function showWelcome(){state.course='';document.getElementById('app').innerHTML=`<span class="preview-ribbon">PRÉVIA INDEPENDENTE</span><header class="public-header"><div class="public-header-inner">${wordmark()}<div class="header-links"><a href="../professor/">Professor</a><a href="https://apps.aems.edu.br/aluno/login" target="_blank" rel="noopener">Área do Aluno</a><a href="../estagio/">Estágio</a></div></div></header><main class="welcome-main"><section class="welcome-intro"><p class="eyebrow">Portal de comunicação acadêmica</p><h1>Escolha o <span>seu curso</span></h1><div class="welcome-chips"><span>Grade semanal</span><span>Salas atualizadas</span><span>Informes acadêmicos</span><span>Datas importantes</span></div></section><div class="course-choices"><button class="course-choice" style="--choice:#3157e2" data-course="ADS"><span class="choice-icon">${svg('code')}</span><span class="choice-copy"><small>Tecnologia e software</small><b>Análise e Desenvolvimento de Sistemas</b><p>Acesse horários, salas e informações acadêmicas de ADS.</p></span><span class="choice-arrow">${svg('arrow')}</span></button><button class="course-choice" style="--choice:#e49c21" data-course="EDC"><span class="choice-icon">${svg('chip')}</span><span class="choice-copy"><small>Engenharia e inovação</small><b>Engenharia de Computação</b><p>Acesse horários, salas e informações acadêmicas de EDC.</p></span><span class="choice-arrow">${svg('arrow')}</span></button><a class="student-choice" href="https://apps.aems.edu.br/aluno/login" target="_blank" rel="noopener"><span class="choice-icon">${svg('external')}</span><span class="choice-copy"><small>Serviços institucionais</small><b>Área do Aluno AEMS</b><p>Boletim, requerimentos e informações financeiras.</p></span><span class="choice-arrow">${svg('arrow')}</span></a></div><div class="welcome-note"><b>Importante</b><p>Este portal facilita a comunicação da coordenação com os estudantes e não substitui a Área do Aluno oficial da AEMS.</p></div></main>`;document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>openCourse(b.dataset.course))}
function navItems(){return [['schedule','home','Horários'],['notices','notice','Informes'],['dates','calendar','Datas'],['teachers','people','Professores']]}
function portalShell(content){const nav=navItems().map(([id,ic,label])=>`<button data-view="${id}" class="${state.view===id?'active':''}">${svg(ic)}<span>${label}</span></button>`).join('');return `<span class="preview-ribbon">PRÉVIA INDEPENDENTE</span><div class="portal"><header class="public-header compact"><div class="public-header-inner">${wordmark()}<div class="header-links"><a href="../professor/">Professor</a><a href="https://apps.aems.edu.br/aluno/login" target="_blank" rel="noopener">Área do Aluno</a><a href="../estagio/">Estágio</a><button data-change-course>Trocar curso</button></div></div></header><main class="main"><section class="course-banner ${state.course.toLowerCase()}"><button class="banner-back" data-change-course aria-label="Trocar curso">${svg('back')}</button><div><small>Curso selecionado</small><h1>${escapeHtml(courseName(state.course))}</h1><p>Horários, salas e comunicação da coordenação.</p></div><span class="course-code">${state.course}</span></section><nav class="floating-nav">${nav}</nav><div class="page-content">${content}</div></main><nav class="bottom-dock">${nav}</nav></div>`}
function hero(){const lessonCount=db.classes.filter(c=>c.courses.includes(state.course)).length,groups=db.groups.filter(g=>(g.cursos||[]).includes(state.course)).length;return `<section class="section-intro"><div><p class="eyebrow">${state.course} · Informação acadêmica</p><h1>${state.view==='schedule'?'Horários e salas':state.view==='notices'?'Informes da coordenação':state.view==='dates'?'Datas importantes':'Professores'}</h1></div><div class="hero-meta"><div class="meta-card"><small>Aulas</small><b>${lessonCount}</b></div><div class="meta-card"><small>Turmas</small><b>${groups}</b></div></div></section>`}
function scheduleView(){const availableGroups=db.groups.filter(g=>(g.cursos||[]).includes(state.course));const groupsOptions=availableGroups.map(g=>`<option value="${g.id}" ${String(state.group)===String(g.id)?'selected':''}>${escapeHtml(g.nome)} · ${state.course}</option>`).join('');const items=db.classes.filter(c=>c.courses.includes(state.course)&&Number(c.day)===state.day&&(state.group==='all'||c.groupIds.includes(Number(state.group))));return `${hero()}<div class="filters"><div class="day-list">${[1,2,3,4,5,6].map(d=>`<button class="day-btn ${state.day===d?'active':''}" data-day="${d}">${SHORT[d]}</button>`).join('')}</div><label class="select-wrap"><select id="group-filter"><option value="all">Todas as turmas</option>${groupsOptions}</select></label></div><div class="section-heading"><div><h2>Aulas de ${DAYS[state.day]}</h2><p>As salas permanecem válidas até uma nova atualização.</p></div><span class="count">${items.length} aula(s)</span></div><div class="schedule-grid">${items.length?items.map((c,i)=>lessonCard(c,i)).join(''):'<div class="empty">Nenhuma aula encontrada para este filtro.</div>'}</div>`}
function lessonCard(c,i){const semi=c.code==='SEMIPRESENCIAL'||c.teacher==='Mediador Pedagógico',r=db.rooms.find(x=>Number(x.id)===Number(c.roomId));const roomName=semi?'Online no grupoau.com.br':r?`${r.nome}`:'Sala ainda não informada pelo professor';const detail=semi?'Ambiente virtual de aprendizagem':r?[r.predio,r.andar].filter(Boolean).join(' · '):'Consulte novamente em breve';return `<article class="lesson" style="animation-delay:${Math.min(i,8)*45}ms;--course-color:${state.course==='ADS'?'#3157e2':'#e49c21'}"><div class="lesson-top"><div class="lesson-time">${semi?'Online':escapeHtml(c.start)}<small>${semi?'Sem bloco de horário':`até ${escapeHtml(c.end)}`}</small></div><div class="lesson-tags">${c.groups.map(g=>`<span class="tag ${state.course==='EDC'?'edc':''}">${escapeHtml(g.nome)} ${state.course}</span>`).join('')}</div></div><h3>${escapeHtml(c.subject)}</h3><span class="teacher">${escapeHtml(c.teacher||'Mediador Pedagógico')}</span><div class="room"><span class="room-icon">${svg('pin')}</span><div><b>${escapeHtml(roomName)}</b><small>${escapeHtml(detail)}</small></div></div></article>`}
function noticesView(){const items=db.notices.filter(n=>(n.cursos||[]).includes(state.course));return `${hero()}<div class="section-heading"><div><h2>Informes da coordenação</h2><p>Recados e orientações para o seu curso.</p></div><span class="count">${items.length} informe(s)</span></div><div class="content-grid">${items.length?items.map((n,i)=>`<article class="notice-card ${i===0?'featured':''}" style="animation-delay:${i*50}ms"><span class="notice-date">${new Date(n.publicado_em).toLocaleDateString('pt-BR')}</span><h3>${escapeHtml(n.titulo)}</h3><p>${escapeHtml(n.conteudo)}</p></article>`).join(''):'<div class="empty">Nenhum informe publicado neste momento.</div>'}</div>`}
function teachersView(){const teacherIds=new Set(db.classes.filter(c=>c.courses.includes(state.course)).map(c=>String(c.professor_id)).filter(Boolean));const items=db.teachers.filter(t=>teacherIds.has(String(t.id)));return `${hero()}<div class="section-heading"><div><h2>Professores</h2><p>Contatos da equipe que atua no curso.</p></div><span class="count">${items.length} docente(s)</span></div><div class="content-grid">${items.length?items.map((t,i)=>{const initials=(t.nome||'P').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return `<article class="teacher-card" style="animation-delay:${i*45}ms"><div class="avatar">${t.avatar_url?`<img class="avatar" src="${escapeHtml(t.avatar_url)}" alt="">`:initials}</div><h3>${escapeHtml(t.nome)}</h3><a href="mailto:${escapeHtml(t.email)}">${escapeHtml(t.email)}</a><div class="teacher-chip">${(t.contatos||[]).map(x=>x==='Somente presencial'?'E-mail':x).join(' · ')||'Contato por e-mail'}</div></article>`}).join(''):'<div class="empty">Nenhum professor vinculado às aulas deste curso.</div>'}</div>`}
function datesView(){const items=db.dates.filter(d=>(d.cursos||[]).includes(state.course));const color=t=>t.includes('Exame')?'#e5b12e':t.includes('Substitutiva')?'#23745d':t.includes('P1')||t.includes('P2')?'#4fae76':'#546ee8';return `${hero()}<div class="section-heading"><div><h2>Datas importantes</h2><p>Avaliações, eventos e marcos acadêmicos.</p></div><span class="count">${items.length} data(s)</span></div><div class="content-grid">${items.length?items.map((d,i)=>`<article class="date-card" style="--date:${color(d.tipo||'')};animation-delay:${i*45}ms"><span class="card-label">${escapeHtml(d.tipo)}</span><h3>${escapeHtml(d.disciplina||d.titulo||'Data importante')}</h3><div class="date-day">${formatDate(d.data)}</div><p>${escapeHtml(d.professor_nome||'Coordenação do curso')}</p>${d.salas?`<p>${escapeHtml(d.salas.nome)} · ${escapeHtml(d.salas.predio||'')}</p>`:''}</article>`).join(''):'<div class="empty">Nenhuma data importante cadastrada para este curso.</div>'}</div>`}
function renderPortal(){let content=state.view==='schedule'?scheduleView():state.view==='notices'?noticesView():state.view==='dates'?datesView():teachersView();document.getElementById('app').innerHTML=portalShell(content);bindPortal()}
function bindPortal(){document.querySelectorAll('[data-change-course]').forEach(b=>b.onclick=showWelcome);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderPortal();scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.day);renderPortal()});document.getElementById('group-filter')?.addEventListener('change',e=>{state.group=e.target.value;renderPortal()})}
function loading(){document.getElementById('app').innerHTML=`<div class="loading"><div><div class="loader-orbit"></div><p>Organizando suas informações…</p></div></div>`}
async function loadData(){const [rooms,groups,classes,links,notices,teachers,dates]=await Promise.all([api.from('salas').select('id,nome,predio,andar').eq('ativa',true).order('nome'),api.from('turmas').select('id,nome,cursos').eq('ativa',true).order('id'),api.from('aulas').select('id,codigo,disciplina,professor_id,professor_nome,turma_id,cursos,dia_semana,inicio,fim,sala_padrao_id').eq('ativa',true).order('inicio'),api.from('aula_turmas').select('aula_id,turma_id,turmas(id,nome,cursos)'),api.from('informes').select('id,titulo,conteudo,cursos,publicado_em').eq('ativo',true).order('publicado_em',{ascending:false}),api.from('professores_publicos').select('*').order('nome'),api.from('avaliacoes').select('*,salas(nome,predio)').eq('ativo',true).order('data')]);const failure=[rooms,groups,classes,links,notices,teachers,dates].find(x=>x.error);if(failure)throw failure.error;db.rooms=rooms.data||[];db.groups=groups.data||[];const byClass={};(links.data||[]).forEach(l=>(byClass[l.aula_id]??=[]).push(l.turmas||{id:l.turma_id,nome:'Turma',cursos:[]}));db.classes=(classes.data||[]).map(c=>({id:c.id,code:c.codigo,subject:c.disciplina,teacher:c.professor_nome,professor_id:c.professor_id,courses:c.cursos||[],day:c.dia_semana,start:String(c.inicio).slice(0,5),end:String(c.fim).slice(0,5),roomId:c.sala_padrao_id,groups:byClass[c.id]||[],groupIds:(byClass[c.id]||[]).map(g=>Number(g.id))}));db.notices=notices.data||[];db.teachers=teachers.data||[];db.dates=dates.data||[]}
async function openCourse(course){state.course=course;state.view='schedule';state.group='all';loading();try{if(!db.classes.length)await loadData();renderPortal()}catch(error){console.error(error);document.getElementById('app').innerHTML=`<div class="error-card"><h2>Não foi possível carregar a prévia</h2><p>Verifique sua conexão e tente novamente.</p><button id="retry">Tentar novamente</button></div>`;document.getElementById('retry').onclick=()=>openCourse(course)}}
showWelcome();
